# Introduction
This notebook is a clone of the run_quantize.py file for mimicking and debugging experiments without using seml and slurm

## 1. Initial Setup

In [1]:
print("Hello World")
!nvidia-smi --query-gpu=memory.free --format=csv | tail -n +2 | awk -F ' ' '{print "Free GPU Memory (GB):", $1 / 1024}'

Hello World
Free GPU Memory (GB): 39.3936

In [2]:

print("\n################################")
print("Setting up environment...")
print("################################\n")

import os
#os.chdir('..')
print("Current Working Directory ", os.getcwd())
import sys
sys.path.append("../") # Add directory containing src/data to path

import importlib
import src  # Assuming src is the package name

# Reload the src module after making changes
importlib.reload(src)

%load_ext autoreload
%autoreload 2

import seml
import re
import shutil

os.environ["TOKENIZERS_PARALLELISM"] = "false"  # Disables parallelism to remove transformers warning

print("\n################################")
print("Setting up cache paths...")
print("################################\n")

os.environ["MKL_SERVICE_FORCE_INTEL"] = "1"
CACHE_PATH = "/nfs/students/daro/.cache/huggingface"
HUB_PATH = "/nfs/students/daro/.cache/huggingface/hub/"

if not os.path.exists(HUB_PATH):
    os.makedirs(HUB_PATH)
    print(f"Creating huggingface hub path at {HUB_PATH}")
    
print(f"Setting cache path to {CACHE_PATH}")
os.environ["TORCH_HOME"] = CACHE_PATH
os.environ["HF_HOME"] = CACHE_PATH

import torch
torch.hub.set_dir(CACHE_PATH)
with torch.no_grad():
    torch.cuda.empty_cache()
    
import logging
logger = logging.getLogger("quant_logger")
    
!cat /proc/meminfo | awk '/MemTotal/ {total=$2} /MemFree/ {free=$2} /MemAvailable/ {available=$2} END {printf "MemTotal: %.2f GB\nMemFree: %.2f GB\nMemAvailable: %.2f GB\n", total/1024/1024, free/1024/1024, available/1024/1024}'
!nvidia-smi --query-gpu=memory.free --format=csv | tail -n +2 | awk -F ' ' '{print "Free GPU Memory (GB):", $1 / 1024}'

print("\n################################")
print("Setting up cuda devices...")
print("################################\n")

if torch.cuda.is_available():
    print("CUDA device is available!")
    # Get the number of available CUDA devices
    num_cuda_devices = torch.cuda.device_count()
    print(f"Number of CUDA devices: {num_cuda_devices}")
    
    # Loop through available devices and get name
    for device_id in range(num_cuda_devices):
        device = torch.device(f"cuda:{device_id}")
        name = torch.cuda.get_device_name(device)
        print(f"  - CUDA Device {device_id+1}: {name}")
else:
    print("CUDA device is not available.")
    
print("\n################################")
print("Authentication with Hugging Face...")
print("################################\n")

import os
from dotenv import load_dotenv
from huggingface_hub import login

load_dotenv()
huggingface_token = os.getenv('HUGGINGFACE_TOKEN')

if huggingface_token is None:
    raise ValueError("Please set the HUGGINGFACE_TOKEN environment variable.")
else:
    print("Hugging Face token loaded successfully.")

login(token=huggingface_token, add_to_git_credential=True)
print("Successfully authenticated with the Hugging Face API.")

print("\n################################")
print("Setting up GPU memory usage list...")
print("################################\n")
# Global list to store GPU memory usage
from src.evaluations.evaluate_memory import record_gpu_memory
gpu_memory_usage = {}
record_gpu_memory(gpu_memory_usage=gpu_memory_usage, context="Warm up notebook")

################################
Setting up environment...
################################

Current Working Directory  /nfs/homedirs/daro/git/quantization-reliability

################################
Setting up cache paths...
################################

Setting cache path to /nfs/students/daro/.cache/huggingface
MemTotal: 1007.72 GB
MemFree: 282.35 GB
MemAvailable: 980.82 GB
Free GPU Memory (GB): 39.3936

################################
Setting up cuda devices...
################################

CUDA device is available!
Number of CUDA devices: 1
  - CUDA Device 1: NVIDIA A100-PCIE-40GB

################################
Authentication with Hugging Face...
################################

/nfs/students/daro/miniconda3/envs/env-quant-rel-310/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Hugging Face token loaded successfully.
Token is valid (permission: write).
Your token has been saved in your configured git credential helpers (store).
Your token has been saved to /nfs/students/daro/.cache/huggingface/token
Login successful
Successfully authenticated with the Hugging Face API.

################################
Setting up GPU memory usage list...
################################

## 2. Loading Datasets

### 2.1 T-Rex

In [ ]:
import os

print("\n################################")
print("Setting up T-REX...")
print("################################\n")

model_name = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"  # Small enough to run on a gpu_gtx1080.

from datasets import load_dataset
ds = load_dataset("relbert/t_rex")
ds

## 3. FKTC Evaluation

In [ ]:
import json
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, GenerationConfig
import os
import pandas as pd

class ResponseGenerator:
    def __init__(self, model_name):
        self.tokenizer = AutoTokenizer.from_pretrained(model_name, device_map="cuda")
        self.model = AutoModelForCausalLM.from_pretrained(model_name, torch_dtype="auto", device_map="cuda")
        self.model.eval()

    def generate_response(self, query, strategy, true_answer, max_new_tokens, temperature):
        prompt = self.get_prompt(query, strategy)
        input_ids = self.tokenizer.encode(prompt, return_tensors='pt').to("cuda")
        generation_config = {
            "temperature": temperature,
            "do_sample": True,
            "top_p": 0.75,
            "top_k": 40,
            "num_beams": 5,
            "num_return_sequences": 3,
            "output_scores": True,
            "output_hidden_states": False,
            "output_attentions": False,
            "return_dict_in_generate": True
        }

        with torch.no_grad():
            outputs = self.model.generate(input_ids, generation_config=GenerationConfig(**generation_config), max_new_tokens=max_new_tokens)

        output_text = self.tokenizer.decode(outputs[0][0], skip_special_tokens=True)
        output_text = self.clean_response(output_text, strategy)
        response_tokens = outputs[0].tolist()
        output_scores = outputs.scores

        is_correct, cumulative_prob, beams_with_probs, top_tokens_with_probs = self.check_answer(response_tokens[0], true_answer, output_scores, input_ids)
        return output_text, is_correct, cumulative_prob, beams_with_probs, top_tokens_with_probs

    def get_prompt(self, query, strategy):
        # Define the prompt formatting based on the selected strategy
        prompt_strategies = {
            "Fact Statement": f"{query} Fact:",
            "Completion": f"{query} The answer is:",
            "Definitive Statement": f"The answer to the question '{query}' is:",
            "True Statement": f"It is true that the answer to '{query}' is:",
            "Declarative Statement": f"{query} The fact is:",
            "Conclusive Statement": f"The final answer to '{query}' is:",
            "Resolved Statement": f"Resolved: '{query}' The answer is:",
            "Ending Completion": f"{query} The final answer is:",
            "Answer Completion": f"{query} The correct answer is:",
            "Plain Completion": f"{query} The answer:",
            "Direct Completion": f"{query} Answer:",
            "Simple Completion": f"{query} Result:",
            "Direct Answer": f"{query} Correct answer:",
            "Answer Statement": f"{query} The exact answer is:",
            "True Completion": f"{query} The true answer is:"
        }
        return prompt_strategies.get(strategy, query)

    def clean_response(self, output_text, strategy):
        # Clean the output text based on the selected strategy
        strategy_endings = {
            "Fact Statement": "Fact:",
            "Completion": "The answer is:",
            "Definitive Statement": "is:",
            "True Statement": "is:",
            "Declarative Statement": "The fact is:",
            "Conclusive Statement": "is:",
            "Resolved Statement": "is:",
            "Ending Completion": "is:",
            "Answer Completion": "The correct answer is:",
            "Plain Completion": "The answer:",
            "Direct Completion": "Answer:",
            "Simple Completion": "Result:",
            "Direct Answer": "Correct answer:",
            "Answer Statement": "The exact answer is:",
            "True Completion": "The true answer is:"
        }
        return output_text.split(strategy_endings.get(strategy, ""))[-1].strip()

    def check_answer(self, response_tokens, true_answer, output_scores, input_ids):
        generated_tokens = response_tokens[input_ids.size(1):]
        if len(generated_tokens) == 0:
            return False, None, None, None
        assert len(generated_tokens) == len(output_scores)
        
        # Generate the four variants of true_answer
        true_answer_lower = true_answer.lower()
        true_answer_title = true_answer.title()
        true_tokens_no_space_lower = self.tokenizer.convert_tokens_to_ids(self.tokenizer.tokenize(true_answer_lower))
        true_tokens_no_space_title = self.tokenizer.convert_tokens_to_ids(self.tokenizer.tokenize(true_answer_title))
        true_tokens_with_space_lower = self.tokenizer.convert_tokens_to_ids(self.tokenizer.tokenize(" " + true_answer_lower))
        true_tokens_with_space_title = self.tokenizer.convert_tokens_to_ids(self.tokenizer.tokenize(" " + true_answer_title))

        variants = [
            true_tokens_no_space_lower,
            true_tokens_no_space_title,
            true_tokens_with_space_lower,
            true_tokens_with_space_title
        ]

        def get_cumulative_probability(true_tokens, idx, output_scores):
            cumulative_prob = 1.0
            top_tokens_with_probs = []
            beams_with_probs = []

            for true_token_idx, true_token in enumerate(true_tokens):
                token_probs = []
                for beam_index, beam_scores in enumerate(output_scores[idx + true_token_idx]):
                    token_probs = torch.softmax(beam_scores, dim=-1)
                    token_prob = token_probs[true_token].item()
                    top_indices = (token_probs >= 0.1).nonzero(as_tuple=True)[0]
                    top_probs = token_probs[top_indices]
                    top_tokens = self.tokenizer.convert_ids_to_tokens(top_indices)
                    top_tokens = [token.replace("Ġ", " ") for token in top_tokens]

                    if true_token in top_indices:
                        top_tokens_with_probs.extend([(token, prob.item()) for token, prob in zip(top_tokens, top_probs)])
                        cumulative_prob *= token_prob
                        beams_with_probs.append({
                            'character_index': idx + true_token_idx,
                            'beam_index': beam_index,
                            'token': self.tokenizer.decode([true_token]),
                            'token_index': true_token,
                            'probability': token_prob
                        })
                        break

            return cumulative_prob, beams_with_probs, top_tokens_with_probs

        # Check each variant
        for variant in variants:
            for idx in range(len(generated_tokens) - len(variant) + 1):
                if generated_tokens[idx:idx + len(variant)] == variant:
                    cumulative_prob, beams_with_probs, top_tokens_with_probs = get_cumulative_probability(variant, idx, output_scores)
                    return True, cumulative_prob, beams_with_probs, top_tokens_with_probs

        return False, None, None, None

In [ ]:
strategies = [
    "Fact Statement", "Completion", "Definitive Statement", "True Statement",
    "Declarative Statement", "Conclusive Statement", "Resolved Statement",
    "Ending Completion", "Answer Completion", "Plain Completion", "Direct Completion",
    "Simple Completion", "Direct Answer", "Answer Statement", "True Completion"
]

In [ ]:
import json
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, GenerationConfig
import os

class MonitorEvaluator:
    def __init__(self, model_name, data_dir, files, generation_config=None, max_new_tokens=15, verbose=True):
        print("Initializing MonitorEvaluator...")
        print(f"Loading model {model_name}...")
        print(f"Loading tokenizer {model_name}...")
        print(f"Loading data from {data_dir}...")
        print(f"Loading files {files}...")
        print(f"Max new tokens: {max_new_tokens}")
        self.generator = ResponseGenerator(model_name)
        self.data_dir = data_dir
        self.files = files
        self.max_new_tokens = max_new_tokens
        self.verbose = verbose
        self.generation_config = generation_config

    def load_json_data(self, filename):
        if self.verbose:
            print(f"Loading data from {filename}...")
        with open(os.path.join(self.data_dir, filename), 'r', encoding='utf8') as f:
            return [json.loads(line) for line in f.readlines()[:4]]  # Load only 4 lines per file for testing

    def evaluate(self):
        if self.verbose:
            print("Evaluating FKTC data...")
        all_results = []
        for file in self.files[:3]:  # Limit to 3 files for testing
            data = self.load_json_data(file)
            relations = data[0]['relations']
            for idx, entry in enumerate(data[1:3]):
                subject = entry['subject']
                true_object = entry['object']
                taxonomy = entry['taxonomy']
                results = []

                for relation in relations[:1]:
                    for strategy in [
                        "Fact Statement", "Completion", "Definitive Statement", "True Statement",
                        "Declarative Statement", "Conclusive Statement", "Resolved Statement",
                        "Ending Completion", "Answer Completion", "Plain Completion", "Direct Completion",
                        "Simple Completion", "Direct Answer", "Answer Statement", "True Completion"
                    ]:
                        # Evaluate original relation
                        prompt = relation.replace("[X]", subject)
                        output_text, is_correct, cumulative_prob, beams_with_probs, top_tokens_with_probs = self.generator.generate_response(prompt, strategy, true_object, self.max_new_tokens, self.generation_config.temperature)
                        results.append({
                            'file': file,
                            'entry': idx,
                            'relation': relation,
                            'prompt': prompt,
                            'subject': subject,
                            'true_object': true_object,
                            'strategy': strategy,
                            'output_text': output_text,
                            'is_correct': is_correct,
                            'cumulative_prob': cumulative_prob,
                            'beams_with_probs': beams_with_probs,
                            'top_tokens_with_probs': top_tokens_with_probs
                        })

                all_results.append(results)
        return all_results

    def save_results(self, results, output_file):
        with open(output_file, 'w', encoding='utf8') as f:
            json.dump(results, f, indent=4)

if __name__ == "__main__":
    model_name = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
    # model_name = "TinyLlama/TinyLlama_v1.1"
    # model_name = "bigscience/bloomz-560m"
    model_name = "bigscience/bloomz-1b1"
    model_name = "meta-llama/Meta-Llama-3-8B"
    # model_name = "meta-llama/Meta-Llama-3-8B-Instruct"
    data_dir = "/nfs/students/daro/data/MONITOR/FKTC"
    files = [
        "P101-subclass.json",
        "P103-subclass.json",
        "P108-subclass.json",
        "P127-subclass.json",
        "P1376-subclass.json",
        "P1412-subclass.json",
        "P159-subclass.json",
        "P17-subclass.json",
        "P176-subclass.json",
        "P178-subclass.json",
        "P19-subclass.json",
        "P20-subclass.json",
        "P264-subclass.json",
        "P27-subclass.json",
        "P276-subclass..json",
        "P30-subclass.json",
        "P364-subclass.json",
        "P37-subclass.json",
        "P495-subclass.json",
        "P740-subclass.json"
    ]
    output_file = "evaluation_results.json"
    max_new_tokens = 15
    generation_config = {
        "temperature": 0.1,
        "top_p": 0.75,
        "top_k": 40,
        "num_beams": 5,
        "num_return_sequences": 1,
        "output_scores": True,
        "output_hidden_states": False,
        "output_attentions": False,
        "return_dict_in_generate": True
    }
    evaluator = MonitorEvaluator(
        model_name=model_name,
        data_dir=data_dir,
        files=files,
        generation_config=generation_config,
        max_new_tokens=max_new_tokens,
        verbose=False
    )
    results = evaluator.evaluate()
    for results_list in results:
        for result in results_list:
            if True:
                print(f"Prompt: {result['prompt']}")
                print(f"Answer: {result['answer']}")
                print(f"True Object: {result['true_object']}")
    print(f"Correct answers: {sum([sum([result['is_correct'] for result in results_list]) for results_list in results])}")
    print(f"Incorrect answers: {sum([sum([not result['is_correct'] for result in results_list]) for results_list in results])}")
    evaluator.save_results(results, output_file)

In [ ]:
import json
import os

class FKTCObjectChecker:
    def __init__(self, data_dir, files):
        self.data_dir = data_dir
        self.files = files

    def load_json_data(self, filename):
        with open(os.path.join(self.data_dir, filename), 'r', encoding='utf8') as f:
            return [json.loads(line) for line in f.readlines()]

    def check_objects_for_multiple_words(self):
        multi_word_objects = {}
        for file in self.files:
            data = self.load_json_data(file)
            for entry in data:
                obj = entry.get('object', "")
                if len(obj.split()) > 1:  # Check if the object contains more than one word
                    if file not in multi_word_objects:
                        multi_word_objects[file] = []
                    multi_word_objects[file].append(obj)
        
        return multi_word_objects

if __name__ == "__main__":
    data_dir = "/nfs/students/daro/data/MONITOR/FKTC"
    files = [
        "P101-subclass.json",
        "P103-subclass.json",
        "P108-subclass.json",
        "P127-subclass.json",
        "P1376-subclass.json",
        "P1412-subclass.json",
        "P159-subclass.json",
        "P17-subclass.json",
        "P176-subclass.json",
        "P178-subclass.json",
        "P19-subclass.json",
        "P20-subclass.json",
        "P264-subclass.json",
        "P27-subclass.json",
        "P276-subclass..json",
        "P30-subclass.json",
        "P364-subclass.json",
        "P37-subclass.json",
        "P495-subclass.json",
        "P740-subclass.json"
    ]

    checker = FKTCObjectChecker(data_dir, files)
    multi_word_objects = checker.check_objects_for_multiple_words()

    if multi_word_objects:
        print("Files with multi-word 'object' values:")
        for file, objects in multi_word_objects.items():
            print(f"\n{file}:")
            for obj in objects:
                print(f"  - {obj}")
    else:
        print("No multi-word 'object' values found in the files.")

In [ ]:
results = evaluator.evaluate()
for results_list in results:
    for result in results_list:
        if result['is_correct']:
            print(f"Prompt: {result['prompt']}")
            print(f"Answer: {result['answer']}")
            print(f"True Object: {result['true_object']}")

In [ ]:
print(sum([sum([result['is_correct'] for result in results_list]) for results_list in results]))
print(sum([sum([not result['is_correct'] for result in results_list]) for results_list in results]))

In [ ]:
for results_list in results:
  for result in results_list:
    if not result['is_correct']:
      print(f"Prompt: {result['prompt']}")
      print(f"Answer: {result['answer']}")
      print(f"True Object: {result['true_object']}")

In [ ]:
import transformers
import torch

model_id = "meta-llama/Meta-Llama-3-8B"
!nvidia-smi --query-gpu=memory.free --format=csv | tail -n +2 | awk -F ' ' '{print "Free GPU Memory (GB):", $1 / 1024}'
pipeline = transformers.pipeline(
  "text-generation", model=model_id, model_kwargs={"torch_dtype": torch.bfloat16}, device_map="cuda"
)
# output = pipeline("What is the capital city of Hungary?", max_new_tokens=15)
output = pipeline("Which city is Chandos Records's corporate headquarters located?", max_new_tokens=100)
answer = output[0]['generated_text']
!nvidia-smi --query-gpu=memory.free --format=csv | tail -n +2 | awk -F ' ' '{print "Free GPU Memory (GB):", $1 / 1024}'
print(output)

In [ ]:
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline
import torch

# Load tokenizer and model with float16 precision
print("Loading model...")
!nvidia-smi --query-gpu=memory.free --format=csv | tail -n +2 | awk -F ' ' '{print "Free GPU Memory (GB):", $1 / 1024}'
model_name = "bigscience/bloomz-560m"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name, torch_dtype="auto", device_map="cuda")
!nvidia-smi --query-gpu=memory.free --format=csv | tail -n +2 | awk -F ' ' '{print "Free GPU Memory (GB):", $1 / 1024}'

# Create a pipeline for text generation
print("Creating pipeline...")
generator = pipeline("text-generation", model=model, tokenizer=tokenizer, device_map="cuda")
!nvidia-smi --query-gpu=memory.free --format=csv | tail -n +2 | awk -F ' ' '{print "Free GPU Memory (GB):", $1 / 1024}'

# Perform inference with the query
print("Performing inference...")
query = "Which city is Chandos Records's corporate headquarters located?"
# query = "What is the capital city of Hungary?"
output = generator(query, max_length=200, num_return_sequences=1)
print(output)

In [ ]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
import json
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, GenerationConfig
import numpy as np

print("Loading tokenizer and model...")
!nvidia-smi --query-gpu=memory.free --format=csv | tail -n +2 | awk -F ' ' '{print "Free GPU Memory (GB):", $1 / 1024}'
# model_name = "bigscience/bloomz-560m"
# model_name = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
# model_name = "TinyLlama/TinyLlama_v1.1"
# model_name = "bigscience/bloomz-560m"
model_name = "bigscience/bloomz-1b1"
# model_name = "meta-llama/Meta-Llama-3-8B"
# model_name = "meta-llama/Meta-Llama-3-8B-Instruct"
tokenizer = AutoTokenizer.from_pretrained(model_name, device_map="cuda")
model = AutoModelForCausalLM.from_pretrained(model_name, torch_dtype="auto", device_map="cuda")

# query = "Which city is Eiffel Tower located in?"
# query = "Spanish. What is the native language of Louis Jules Trochu?"
query = "Which industry does Alan Turing work in?"
# query = "What is the location of Simcoe Composite School?"
input_ids = tokenizer.encode(query, return_tensors='pt').to("cuda")

max_length = 50
generation_config = {
    "temperature": 1,
    "top_p": 0.75,
    "top_k": 40,
    "num_beams": 5,
    "num_return_sequences": 1,
    "output_scores": True,
    "output_hidden_states": False,
    "output_attentions": False,
    "return_dict_in_generate": True
}

print("Generating output...")
!nvidia-smi --query-gpu=memory.free --format=csv | tail -n +2 | awk -F ' ' '{print "Free GPU Memory (GB):", $1 / 1024}'
with torch.no_grad():
    output_ids = model.generate(input_ids, generation_config=GenerationConfig(**generation_config), max_new_tokens=15)

print("Decoding output...")
!nvidia-smi --query-gpu=memory.free --format=csv | tail -n +2 | awk -F ' ' '{print "Free GPU Memory (GB):", $1 / 1024}'
output_text = tokenizer.decode(output_ids[0][0], skip_special_tokens=True)
print(output_text)

In [ ]:
from transformers import AutoTokenizer
import transformers 
import torch
model = "TinyLlama/TinyLlama_v1.1"
# model = "bigscience/bloomz-560m"
tokenizer = AutoTokenizer.from_pretrained(model)
pipeline = transformers.pipeline(
    "text-generation",
    model=model,
    torch_dtype=torch.float16,
    device_map="auto",
)

sequences = pipeline(
    query,
    do_sample=True,
    top_k=10,
    num_return_sequences=1,
    repetition_penalty=1.5,
    eos_token_id=tokenizer.eos_token_id,
    max_new_tokens=15,
)
for seq in sequences:
    print(f"Result: {seq['generated_text']}")

### 3.1 All strategies

In [ ]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, GenerationConfig
import pandas as pd

class ResponseGenerator:
    def __init__(self, model_name):
        self.tokenizer = AutoTokenizer.from_pretrained(model_name, device_map="cuda")
        self.model = AutoModelForCausalLM.from_pretrained(model_name, torch_dtype="auto", device_map="cuda")
        self.model.eval()

    def generate_response(self, prompt, max_new_tokens, temperature):
        input_ids = self.tokenizer.encode(prompt, return_tensors='pt').to("cuda")
        generation_config = {
            "temperature": temperature,
            "do_sample": True,
            "top_p": 0.75,
            "top_k": 40,
            "num_beams": 5,
            "num_return_sequences": 1,
            "output_scores": True,
            "output_hidden_states": False,
            "output_attentions": False,
            "return_dict_in_generate": True
        }

        with torch.no_grad():
            outputs = self.model.generate(input_ids, generation_config=GenerationConfig(**generation_config), max_new_tokens=max_new_tokens)

        output_text = self.tokenizer.decode(outputs[0][0], skip_special_tokens=True)
        probabilities = self.extract_probabilities(outputs)
        return output_text, probabilities

    def extract_probabilities(self, outputs):
        probabilities = []
        for score in outputs.scores:
            probs = torch.softmax(score[0], dim=-1)
            top_prob, top_idx = torch.max(probs, dim=-1)
            probabilities.append((self.tokenizer.decode(top_idx), top_prob.item()))
        return probabilities

def apply_prompt_strategy(query, strategy):
    if strategy == "Direct Instruction":
        return f"Please answer the following question in one word.\nQuestion: {query}\nAnswer:"
    elif strategy == "Contextual Prompts":
        return f"{query} (Please answer in one word)"
    elif strategy == "Explicit Formatting":
        return f"What is the location of {query}?\nAnswer (one word):"
    elif strategy == "Question-Answer Pairs":
        return f"QSTN: What is the capital of France?\nANSR: Paris\nQSTN: What is the capital of Germany?\nANSR: Berlin\nQSTN: {query}\nANSR:"
    elif strategy == "Negative Examples":
        return f"QSTN: What is the capital of France?\nANSR: Berlin (incorrect)\nANSR: Paris (correct)\nQSTN: {query}\nANSR:"
    elif strategy == "Direct Answer Request":
        return f"Give a concise answer: {query}\nAnswer:"
    elif strategy == "Role Play":
        return f"You are a geography expert known for your concise answers.\nQuestion: {query}\nAnswer:"
    elif strategy == "Simplified Question":
        return f"Where is {query} located?\nAnswer:"
    elif strategy == "List Format":
        return f"List of schools and their locations:\n1. Harvard University - USA\n2. University of Cambridge - UK\n3. {query} -"
    elif strategy == "Multiple Choice":
        return f"Select the correct location of {query}:\nA) USA\nB) UK\nC) Canada\nAnswer:"
    elif strategy == "Fill-in-the-Blank":
        return f"{query} is located in _____.\nAnswer:"
    elif strategy == "Structured Answer Prompt":
        return f"Question: {query}\nAnswer (one word):"
    else:
        return query

# Example usage:
model_names = [
    "bigscience/bloomz-560m",
    "bigscience/bloomz-1b1",
    "openai-community/gpt2-large",
    "EleutherAI/gpt-neo-1.3B",
    "TinyLlama/TinyLlama_v1.1",
    "TinyLlama/TinyLlama-1.1B-Chat-v1.0",
    #"meta-llama/Meta-Llama-3-8B",
    #"meta-llama/Meta-Llama-3-8B-Instruct",
]
queries = [
    "What is the location of Simcoe Composite School?",
    "What is Alan Turing's area of expertise?",
    "What is the native language of Louis Jules Trochu?",
    "What is the capital city of Italy?",
    "What is the main ingredient in sushi?"
]
true_answers = [
    "Canada",
    "logic",
    "French",
    "Rome",
    "rice"
]
max_new_tokens_list = [5, 15, 25]
temperature_list = [0.1, 1]
strategies = [
    # "Direct Instruction",
    # "Contextual Prompts",
    # "Explicit Formatting",
    "Question-Answer Pairs",
    "Negative Examples",
    # "Direct Answer Request",
    # "Role Play",
    # "Simplified Question",
    # "List Format",
    # "Multiple Choice",
    # "Fill-in-the-Blank",
    # "Structured Answer Prompt"
]

# Initialize a list to store the results
results = []

for model_name in model_names:
    generator = ResponseGenerator(model_name)
    for query, true_answer in zip(queries, true_answers):
        for max_new_tokens in max_new_tokens_list:
            for temperature in temperature_list:
                for strategy in strategies:
                    print(f"Model: {model_name}, Query: {query}, Strategy: {strategy}, Max New Tokens: {max_new_tokens}, Temperature: {temperature}")
                    prompt = apply_prompt_strategy(query, strategy)
                    output_text, probabilities = generator.generate_response(prompt, max_new_tokens, temperature)
                    if output_text.startswith(prompt):
                        output_text = output_text[len(prompt):].strip()
                    results.append({
                        "Model": model_name,
                        "Query": query,
                        "Strategy": strategy,
                        "Max New Tokens": max_new_tokens,
                        "Temperature": temperature,
                        "True Answer": true_answer,
                        "Output": output_text,
                        "Probabilities": probabilities
                    })

# Convert the results list to a pandas DataFrame
df = pd.DataFrame(results)

# Print the DataFrame
print(df)

# Export the DataFrame to an Excel file
df.to_excel("results_07_25_qa_negative.xlsx", index=False)

### 3.3 Cleaned

In [8]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, GenerationConfig
import pandas as pd
import numpy as np

def get_prompt(query, strategy):
    if strategy == "Fact Statement":
        prompt = f"{query} Fact:"
    elif strategy == "Completion":
        prompt = f"The answer is:"
    elif strategy == "Definitive Statement":
        prompt = f"The answer to the question '{query}' is:"
    # Add other strategies if needed
    return prompt

def clean_response(output_text, strategy):
    if strategy == "Fact Statement":
        output_text = output_text.split("Fact:")[-1].strip()
    elif strategy == "Completion":
        output_text = output_text.split("The answer is:")[-1].strip()
    elif strategy == "Definitive Statement":
        output_text = output_text.split("is:")[-1].strip()
    # Add other strategies if needed
    return output_text

def calculate_entropy(probs):
    return -np.sum(probs * np.log(probs))

class ResponseGenerator:
    def __init__(self, model_name):
        self.tokenizer = AutoTokenizer.from_pretrained(model_name, device_map="cuda")
        self.model = AutoModelForCausalLM.from_pretrained(model_name, torch_dtype="auto", device_map="cuda")
        
        # Set pad_token_id to eos_token_id to avoid the warning
        self.tokenizer.pad_token_id = self.tokenizer.eos_token_id
        
        self.model.eval()

    def generate_response(self, query, strategy, true_answer, max_new_tokens, temperature):
        prompt = get_prompt(query, strategy)
        inputs = self.tokenizer(prompt, return_tensors='pt').to("cuda")
        
        generation_config = {
            "temperature": temperature,
            "do_sample": True,  # Enable multinomial sampling
            "top_p": 0.75,
            "top_k": 40,
            "output_scores": True,
            "output_hidden_states": False,
            "output_attentions": False,
            "return_dict_in_generate": True,
            "pad_token_id": self.tokenizer.eos_token_id  # Set pad_token_id to avoid warning
        }

        with torch.no_grad():
            outputs = self.model.generate(
                inputs['input_ids'],
                attention_mask=inputs['attention_mask'],  # Provide attention_mask to avoid the warning
                generation_config=GenerationConfig(**generation_config),
                max_new_tokens=max_new_tokens
            )

        output_text = self.tokenizer.decode(outputs[0][0], skip_special_tokens=True)
        output_text = clean_response(output_text, strategy)
        response_tokens = outputs.sequences[0].tolist()

        # Calculate probabilities for the generated part
        probs = []
        token_probs = []
        sequence = outputs.sequences[0]
        cum_prob = 1.0
        shift_idx = len(sequence) - len(outputs.scores)  # Position to start processing tokens
        for pos_idx, beam_scores in enumerate(outputs.scores):
            softmax_scores = torch.softmax(beam_scores, dim=-1)
            token_id = sequence[pos_idx + shift_idx]
            token_prob = softmax_scores[0][token_id].item()
            token = self.tokenizer.decode([token_id])
            token_probs.append((token, round(token_prob, 4)))
            cum_prob *= token_prob
            probs.append(token_prob)
        
        probs = torch.tensor(probs)
        adj_prob = torch.exp((len(probs) ** -1) * torch.sum(torch.log(probs)))
        
        # Calculate entropy score
        entropy = calculate_entropy(np.array(probs))

        # Check if the generated answer is correct
        is_correct = true_answer.lower() in output_text.lower()

        return output_text, cum_prob, adj_prob, entropy, token_probs, is_correct

# Example usage:
model_names = ["meta-llama/Meta-Llama-3-8B"]
queries = [
    "What is the location of Simcoe Composite School?",
    "musical. What is Alan Turing's area of expertise?",
    "Latin. What is the native language of Louis Jules Trochu?",
    "What is the top speed of a Formula 1 car?",
    "What is the main ingredient of a Caesar salad?",
    "What is the capital city of France?",
    "Who discovered penicillin?",
    "What language is primarily spoken in Brazil?",
    "What is the primary spice used in curry?",
    "Who wrote the play 'Hamlet'?",
    "What is the primary color of bananas?",
    "Who is the author of '1984'?"
]
true_answers = [
    "Canada",
    "logic",
    "French",
    "360 km/h",
    "lettuce",
    "Paris",
    "Alexander Fleming",
    "Portuguese",
    "Turmeric",
    "William Shakespeare",
    "yellow",
    "George Orwell"
]
max_new_tokens_list = [15, 25]
temperature_list = [0.1]
strategies = [
    "Fact Statement",
    "Completion",
    # "Definitive Statement"
]

# Initialize a list to store the results
results = []
total_queries = 0
repeats = 5  # Number of times to repeat each generation

total_num_queries = len(model_names) * len(queries) * len(max_new_tokens_list) * len(temperature_list) * len(strategies) * repeats

for model_name in model_names:
    generator = ResponseGenerator(model_name)
    for query_idx, (query, true_answer) in enumerate(zip(queries, true_answers)):
        for max_new_tokens in max_new_tokens_list:
            for temperature in temperature_list:
                for strategy in strategies:
                    for run in range(repeats):
                        print(f"TOTAL: {total_queries + 1}/{total_num_queries}, MODEL: {model_name}, QUERY: {query_idx}, STRATEGY: {strategy}, MAX_NEW_TOKENS: {max_new_tokens}, TEMP: {temperature}, RUN: {run + 1}/{repeats}")
                        output_text, cum_prob, adj_prob, entropy, token_probs, is_correct = generator.generate_response(query, strategy, true_answer, max_new_tokens, temperature)
                        results.append({
                            "model": model_name,
                            "query": query,
                            "max_new_tokens": max_new_tokens,
                            "temp": temperature,
                            "strategy": strategy,
                            "true_answer": true_answer,
                            "output_text": output_text,
                            "is_correct": is_correct,
                            "cum_prob": round(cum_prob, 4),
                            "adj_prob": round(adj_prob.item(), 4),
                            "entropy": round(entropy, 4),
                            "token_probs": token_probs,  # Now includes tuples of (token, prob)
                            "run": run + 1  # Indicate which run this is
                        })
                        total_queries += 1
                        print(f"OUTPUT_TEXT: {output_text}, IS_CORRECT: {is_correct}, CUM_PROB: {cum_prob}")

# Convert the results list to a pandas DataFrame
df = pd.DataFrame(results)

# Print the DataFrame
print(df)

# Export the DataFrame to an Excel file
df.to_excel("multinomial_sampling_llama_5_runs-v2.xlsx", index=False)

Loading checkpoint shards: 100%|██████████| 4/4 [00:03<00:00,  1.20it/s]

TOTAL: 1/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Fact Statement, MAX_NEW_TOKENS: 15, TEMP: 0.1, RUN: 1/5
OUTPUT_TEXT: Simcoe Composite School is located at 1 Simcoe Street, Simcoe, IS_CORRECT: False, CUM_PROB: 1.0
TOTAL: 2/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Fact Statement, MAX_NEW_TOKENS: 15, TEMP: 0.1, RUN: 2/5
OUTPUT_TEXT: Simcoe Composite School is located at 1 Simcoe Street, Simcoe, IS_CORRECT: False, CUM_PROB: 1.0
TOTAL: 3/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Fact Statement, MAX_NEW_TOKENS: 15, TEMP: 0.1, RUN: 3/5
OUTPUT_TEXT: Simcoe Composite School is located at 1 Simcoe Street, Simcoe, IS_CORRECT: False, CUM_PROB: 1.0
TOTAL: 4/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Fact Statement, MAX_NEW_TOKENS: 15, TEMP: 0.1, RUN: 4/5
OUTPUT_TEXT: Simcoe Composite School is located at 1 Simcoe Street, Simcoe, IS_CORRECT: False, CUM_PROB: 1.0
TOTAL: 5/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Fact Statement, MAX_NEW_TOKENS: 15, TEMP: 0.1, RUN: 5/5
OUTPUT_TEXT: Simcoe Composite School is located at 1 Simcoe Street, Simcoe, IS_CORRECT: False, CUM_PROB: 1.0
TOTAL: 6/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Completion, MAX_NEW_TOKENS: 15, TEMP: 0.1, RUN: 1/5
OUTPUT_TEXT: it, IS_CORRECT: False, CUM_PROB: 0.38864994049072266
TOTAL: 7/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Completion, MAX_NEW_TOKENS: 15, TEMP: 0.1, RUN: 2/5
OUTPUT_TEXT: it depends. The answer depends on the type of business you are in,, IS_CORRECT: False, CUM_PROB: 0.38864994049072266
TOTAL: 8/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Completion, MAX_NEW_TOKENS: 15, TEMP: 0.1, RUN: 3/5
OUTPUT_TEXT: it, IS_CORRECT: False, CUM_PROB: 0.38864994049072266
TOTAL: 9/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Completion, MAX_NEW_TOKENS: 15, TEMP: 0.1, RUN: 4/5
OUTPUT_TEXT: yes, you can. But you should be aware of the risks involved., IS_CORRECT: False, CUM_PROB: 0.05567503720521927
TOTAL: 10/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Completion, MAX_NEW_TOKENS: 15, TEMP: 0.1, RUN: 5/5
OUTPUT_TEXT: it, IS_CORRECT: False, CUM_PROB: 0.38864994049072266
TOTAL: 11/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Fact Statement, MAX_NEW_TOKENS: 25, TEMP: 0.1, RUN: 1/5
OUTPUT_TEXT: Simcoe Composite School is located at 1 Simcoe Street, Simcoe, Ontario, N3Y 4H3, IS_CORRECT: False, CUM_PROB: 1.0
TOTAL: 12/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Fact Statement, MAX_NEW_TOKENS: 25, TEMP: 0.1, RUN: 2/5
OUTPUT_TEXT: Simcoe Composite School is located at 1 Simcoe Street, Simcoe, Ontario, N3Y 4H3, IS_CORRECT: False, CUM_PROB: 1.0
TOTAL: 13/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Fact Statement, MAX_NEW_TOKENS: 25, TEMP: 0.1, RUN: 3/5
OUTPUT_TEXT: Simcoe Composite School is located at 1 Simcoe Street, Simcoe, Ontario, N3Y 4H3, IS_CORRECT: False, CUM_PROB: 1.0
TOTAL: 14/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Fact Statement, MAX_NEW_TOKENS: 25, TEMP: 0.1, RUN: 4/5
OUTPUT_TEXT: Simcoe Composite School is located at 1 Simcoe Street, Simcoe, Ontario, N3Y 4H3, IS_CORRECT: False, CUM_PROB: 1.0
TOTAL: 15/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Fact Statement, MAX_NEW_TOKENS: 25, TEMP: 0.1, RUN: 5/5
OUTPUT_TEXT: Simcoe Composite School is located at 1 Simcoe Street, Simcoe, Ontario, N3Y 4H3, IS_CORRECT: False, CUM_PROB: 1.0
TOTAL: 16/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Completion, MAX_NEW_TOKENS: 25, TEMP: 0.1, RUN: 1/5
OUTPUT_TEXT: yes, you can. But it’s not as easy as it sounds. You need to know what you’re doing and have, IS_CORRECT: False, CUM_PROB: 0.027837518602609634
TOTAL: 17/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Completion, MAX_NEW_TOKENS: 25, TEMP: 0.1, RUN: 2/5
OUTPUT_TEXT: yes, you can. But it’s not as simple as it sounds. There are a few things you need to know before, IS_CORRECT: False, CUM_PROB: 0.05567503720521927
TOTAL: 18/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Completion, MAX_NEW_TOKENS: 25, TEMP: 0.1, RUN: 3/5
OUTPUT_TEXT: yes, you can. But you should be aware of the risks involved. If you are not careful, you could end up, IS_CORRECT: False, CUM_PROB: 0.03626420878921355
TOTAL: 19/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Completion, MAX_NEW_TOKENS: 25, TEMP: 0.1, RUN: 4/5
OUTPUT_TEXT: it depends. The, IS_CORRECT: False, CUM_PROB: 0.38864994049072266
TOTAL: 20/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Completion, MAX_NEW_TOKENS: 25, TEMP: 0.1, RUN: 5/5
OUTPUT_TEXT: yes, you can. But you need to be careful. The reason is that the IRS has a very strict definition of what, IS_CORRECT: False, CUM_PROB: 0.02163809989662724
TOTAL: 21/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 1, STRATEGY: Fact Statement, MAX_NEW_TOKENS: 15, TEMP: 0.1, RUN: 1/5
OUTPUT_TEXT: Alan Turing was a British mathematician, logician, cryptanalyst,, IS_CORRECT: True, CUM_PROB: 1.0
TOTAL: 22/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 1, STRATEGY: Fact Statement, MAX_NEW_TOKENS: 15, TEMP: 0.1, RUN: 2/5
OUTPUT_TEXT: Alan Turing was a British mathematician, logician, cryptanalyst,, IS_CORRECT: True, CUM_PROB: 1.0
TOTAL: 23/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 1, STRATEGY: Fact Statement, MAX_NEW_TOKENS: 15, TEMP: 0.1, RUN: 3/5
OUTPUT_TEXT: Alan Turing was a British mathematician, logician, cryptanalyst,, IS_CORRECT: True, CUM_PROB: 1.0
TOTAL: 24/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 1, STRATEGY: Fact Statement, MAX_NEW_TOKENS: 15, TEMP: 0.1, RUN: 4/5
OUTPUT_TEXT: Alan Turing was a British mathematician, logician, cryptanalyst,, IS_CORRECT: True, CUM_PROB: 1.0
TOTAL: 25/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 1, STRATEGY: Fact Statement, MAX_NEW_TOKENS: 15, TEMP: 0.1, RUN: 5/5
OUTPUT_TEXT: Alan Turing was a British mathematician, logician, cryptanalyst,, IS_CORRECT: True, CUM_PROB: 1.0
TOTAL: 26/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 1, STRATEGY: Completion, MAX_NEW_TOKENS: 15, TEMP: 0.1, RUN: 1/5
OUTPUT_TEXT: yes, you can. But you should be aware of the risks involved., IS_CORRECT: False, CUM_PROB: 0.05567503720521927
TOTAL: 27/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 1, STRATEGY: Completion, MAX_NEW_TOKENS: 15, TEMP: 0.1, RUN: 2/5
OUTPUT_TEXT: it depends. The answer depends on the type of business you are in,, IS_CORRECT: False, CUM_PROB: 0.38864994049072266
TOTAL: 28/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 1, STRATEGY: Completion, MAX_NEW_TOKENS: 15, TEMP: 0.1, RUN: 3/5
OUTPUT_TEXT: yes, you can. But you need to be careful. The reason is, IS_CORRECT: False, CUM_PROB: 0.027837518602609634
TOTAL: 29/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 1, STRATEGY: Completion, MAX_NEW_TOKENS: 15, TEMP: 0.1, RUN: 4/5
OUTPUT_TEXT: it depends. The answer depends on the type of business you are in,, IS_CORRECT: False, CUM_PROB: 0.38864994049072266
TOTAL: 30/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 1, STRATEGY: Completion, MAX_NEW_TOKENS: 15, TEMP: 0.1, RUN: 5/5
OUTPUT_TEXT: it, IS_CORRECT: False, CUM_PROB: 0.38864994049072266
TOTAL: 31/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 1, STRATEGY: Fact Statement, MAX_NEW_TOKENS: 25, TEMP: 0.1, RUN: 1/5
OUTPUT_TEXT: Alan Turing was a British mathematician, logician, cryptanalyst, and computer scientist. Alan Turing was a British mathematic, IS_CORRECT: True, CUM_PROB: 0.3486451506614685
TOTAL: 32/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 1, STRATEGY: Fact Statement, MAX_NEW_TOKENS: 25, TEMP: 0.1, RUN: 2/5
OUTPUT_TEXT: Alan Turing was a British mathematician, logician, cryptanalyst, and computer scientist. He was highly influential in the, IS_CORRECT: True, CUM_PROB: 0.6513549089431763
TOTAL: 33/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 1, STRATEGY: Fact Statement, MAX_NEW_TOKENS: 25, TEMP: 0.1, RUN: 3/5
OUTPUT_TEXT: Alan Turing was a British mathematician, logician, cryptanalyst, and computer scientist. He was highly influential in the, IS_CORRECT: True, CUM_PROB: 0.6513549089431763
TOTAL: 34/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 1, STRATEGY: Fact Statement, MAX_NEW_TOKENS: 25, TEMP: 0.1, RUN: 4/5
OUTPUT_TEXT: Alan Turing was a British mathematician, logician, cryptanalyst, and computer scientist. He was highly influential in the, IS_CORRECT: True, CUM_PROB: 0.6513549089431763
TOTAL: 35/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 1, STRATEGY: Fact Statement, MAX_NEW_TOKENS: 25, TEMP: 0.1, RUN: 5/5
OUTPUT_TEXT: Alan Turing was a British mathematician, logician, cryptanalyst, and computer scientist. He was highly influential in the, IS_CORRECT: True, CUM_PROB: 0.6513549089431763
TOTAL: 36/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 1, STRATEGY: Completion, MAX_NEW_TOKENS: 25, TEMP: 0.1, RUN: 1/5
OUTPUT_TEXT: yes, you can. But you should be aware of the risks involved. If you are not careful, you could end up, IS_CORRECT: False, CUM_PROB: 0.03626420878921355
TOTAL: 37/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 1, STRATEGY: Completion, MAX_NEW_TOKENS: 25, TEMP: 0.1, RUN: 2/5
OUTPUT_TEXT: it depends. The, IS_CORRECT: False, CUM_PROB: 0.38864994049072266
TOTAL: 38/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 1, STRATEGY: Completion, MAX_NEW_TOKENS: 25, TEMP: 0.1, RUN: 3/5
OUTPUT_TEXT: it depends. The, IS_CORRECT: False, CUM_PROB: 0.38864994049072266
TOTAL: 39/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 1, STRATEGY: Completion, MAX_NEW_TOKENS: 25, TEMP: 0.1, RUN: 4/5
OUTPUT_TEXT: it depends. The, IS_CORRECT: False, CUM_PROB: 0.38864994049072266
TOTAL: 40/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 1, STRATEGY: Completion, MAX_NEW_TOKENS: 25, TEMP: 0.1, RUN: 5/5
OUTPUT_TEXT: it depends. The answer depends on the type of business you are in, the type of customers you have, and the type, IS_CORRECT: False, CUM_PROB: 0.25314904659910553
TOTAL: 41/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 2, STRATEGY: Fact Statement, MAX_NEW_TOKENS: 15, TEMP: 0.1, RUN: 1/5
OUTPUT_TEXT: Louis Jules Trochu is the native French Speaker., IS_CORRECT: True, CUM_PROB: 0.5
TOTAL: 42/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 2, STRATEGY: Fact Statement, MAX_NEW_TOKENS: 15, TEMP: 0.1, RUN: 2/5
OUTPUT_TEXT: Louis Jules Trochu is the native French Speaker., IS_CORRECT: True, CUM_PROB: 0.5
TOTAL: 43/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 2, STRATEGY: Fact Statement, MAX_NEW_TOKENS: 15, TEMP: 0.1, RUN: 3/5
OUTPUT_TEXT: Louis Jules Trochu is the native French Speaker., IS_CORRECT: True, CUM_PROB: 0.5
TOTAL: 44/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 2, STRATEGY: Fact Statement, MAX_NEW_TOKENS: 15, TEMP: 0.1, RUN: 4/5
OUTPUT_TEXT: Louis Jules Trochu was born on the 12th of March,, IS_CORRECT: False, CUM_PROB: 0.5
TOTAL: 45/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 2, STRATEGY: Fact Statement, MAX_NEW_TOKENS: 15, TEMP: 0.1, RUN: 5/5
OUTPUT_TEXT: Louis Jules Trochu was born on the 12th of March,, IS_CORRECT: False, CUM_PROB: 0.5
TOTAL: 46/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 2, STRATEGY: Completion, MAX_NEW_TOKENS: 15, TEMP: 0.1, RUN: 1/5
OUTPUT_TEXT: it, IS_CORRECT: False, CUM_PROB: 0.38864994049072266
TOTAL: 47/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 2, STRATEGY: Completion, MAX_NEW_TOKENS: 15, TEMP: 0.1, RUN: 2/5
OUTPUT_TEXT: it depends. The answer depends on the type of business you are in,, IS_CORRECT: False, CUM_PROB: 0.38864994049072266
TOTAL: 48/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 2, STRATEGY: Completion, MAX_NEW_TOKENS: 15, TEMP: 0.1, RUN: 3/5
OUTPUT_TEXT: it, IS_CORRECT: False, CUM_PROB: 0.38864994049072266
TOTAL: 49/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 2, STRATEGY: Completion, MAX_NEW_TOKENS: 15, TEMP: 0.1, RUN: 4/5
OUTPUT_TEXT: it, IS_CORRECT: False, CUM_PROB: 0.38864994049072266
TOTAL: 50/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 2, STRATEGY: Completion, MAX_NEW_TOKENS: 15, TEMP: 0.1, RUN: 5/5
OUTPUT_TEXT: it, IS_CORRECT: False, CUM_PROB: 0.38864994049072266
TOTAL: 51/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 2, STRATEGY: Fact Statement, MAX_NEW_TOKENS: 25, TEMP: 0.1, RUN: 1/5
OUTPUT_TEXT: Louis Jules Trochu was born on the 12th of March, 1815 (died on March 7, IS_CORRECT: False, CUM_PROB: 0.5
TOTAL: 52/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 2, STRATEGY: Fact Statement, MAX_NEW_TOKENS: 25, TEMP: 0.1, RUN: 2/5
OUTPUT_TEXT: Louis Jules Trochu was born on the 12th of March, 1815 (died on March 7, IS_CORRECT: False, CUM_PROB: 0.5
TOTAL: 53/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 2, STRATEGY: Fact Statement, MAX_NEW_TOKENS: 25, TEMP: 0.1, RUN: 3/5
OUTPUT_TEXT: Louis Jules Trochu is the native French Speaker., IS_CORRECT: True, CUM_PROB: 0.5
TOTAL: 54/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 2, STRATEGY: Fact Statement, MAX_NEW_TOKENS: 25, TEMP: 0.1, RUN: 4/5
OUTPUT_TEXT: Louis Jules Trochu is the native French Speaker., IS_CORRECT: True, CUM_PROB: 0.5
TOTAL: 55/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 2, STRATEGY: Fact Statement, MAX_NEW_TOKENS: 25, TEMP: 0.1, RUN: 5/5
OUTPUT_TEXT: Louis Jules Trochu is the native French Speaker., IS_CORRECT: True, CUM_PROB: 0.5
TOTAL: 56/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 2, STRATEGY: Completion, MAX_NEW_TOKENS: 25, TEMP: 0.1, RUN: 1/5
OUTPUT_TEXT: it depends. The answer depends on the type of business you are in, the type of customers you have, and the type, IS_CORRECT: False, CUM_PROB: 0.25314904659910553
TOTAL: 57/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 2, STRATEGY: Completion, MAX_NEW_TOKENS: 25, TEMP: 0.1, RUN: 2/5
OUTPUT_TEXT: it depends. The, IS_CORRECT: False, CUM_PROB: 0.38864994049072266
TOTAL: 58/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 2, STRATEGY: Completion, MAX_NEW_TOKENS: 25, TEMP: 0.1, RUN: 3/5
OUTPUT_TEXT: it depends. The answer depends on the type of business you are in, the type of customers you have, and the type, IS_CORRECT: False, CUM_PROB: 0.25314904659910553
TOTAL: 59/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 2, STRATEGY: Completion, MAX_NEW_TOKENS: 25, TEMP: 0.1, RUN: 4/5
OUTPUT_TEXT: it depends. The, IS_CORRECT: False, CUM_PROB: 0.38864994049072266
TOTAL: 60/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 2, STRATEGY: Completion, MAX_NEW_TOKENS: 25, TEMP: 0.1, RUN: 5/5
OUTPUT_TEXT: yes, you can. But it’s not as easy as it sounds. There are a few things you need to know before, IS_CORRECT: False, CUM_PROB: 0.027837518602609634
TOTAL: 61/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 3, STRATEGY: Fact Statement, MAX_NEW_TOKENS: 15, TEMP: 0.1, RUN: 1/5
OUTPUT_TEXT: Formula 1 cars are the fastest road racing cars in the world. They, IS_CORRECT: False, CUM_PROB: 0.25
TOTAL: 62/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 3, STRATEGY: Fact Statement, MAX_NEW_TOKENS: 15, TEMP: 0.1, RUN: 2/5
OUTPUT_TEXT: The top speed of a Formula 1 car is 360 km/h (, IS_CORRECT: True, CUM_PROB: 0.5
TOTAL: 63/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 3, STRATEGY: Fact Statement, MAX_NEW_TOKENS: 15, TEMP: 0.1, RUN: 3/5
OUTPUT_TEXT: Formula 1 cars are the fastest road-racing cars in the world., IS_CORRECT: False, CUM_PROB: 0.25
TOTAL: 64/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 3, STRATEGY: Fact Statement, MAX_NEW_TOKENS: 15, TEMP: 0.1, RUN: 4/5
OUTPUT_TEXT: The top speed of a Formula 1 car is 360 km/h (, IS_CORRECT: True, CUM_PROB: 0.5
TOTAL: 65/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 3, STRATEGY: Fact Statement, MAX_NEW_TOKENS: 15, TEMP: 0.1, RUN: 5/5
OUTPUT_TEXT: Formula 1 cars are the fastest road racing cars in the world. They, IS_CORRECT: False, CUM_PROB: 0.25
TOTAL: 66/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 3, STRATEGY: Completion, MAX_NEW_TOKENS: 15, TEMP: 0.1, RUN: 1/5
OUTPUT_TEXT: it depends. The answer depends on the type of business you are in,, IS_CORRECT: False, CUM_PROB: 0.38864994049072266
TOTAL: 67/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 3, STRATEGY: Completion, MAX_NEW_TOKENS: 15, TEMP: 0.1, RUN: 2/5
OUTPUT_TEXT: it, IS_CORRECT: False, CUM_PROB: 0.38864994049072266
TOTAL: 68/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 3, STRATEGY: Completion, MAX_NEW_TOKENS: 15, TEMP: 0.1, RUN: 3/5
OUTPUT_TEXT: it, IS_CORRECT: False, CUM_PROB: 0.38864994049072266
TOTAL: 69/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 3, STRATEGY: Completion, MAX_NEW_TOKENS: 15, TEMP: 0.1, RUN: 4/5
OUTPUT_TEXT: it, IS_CORRECT: False, CUM_PROB: 0.38864994049072266
TOTAL: 70/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 3, STRATEGY: Completion, MAX_NEW_TOKENS: 15, TEMP: 0.1, RUN: 5/5
OUTPUT_TEXT: it, IS_CORRECT: False, CUM_PROB: 0.38864994049072266
TOTAL: 71/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 3, STRATEGY: Fact Statement, MAX_NEW_TOKENS: 25, TEMP: 0.1, RUN: 1/5
OUTPUT_TEXT: Formula 1 cars are the fastest road-racing cars in the world. They are designed to go around a track as fast, IS_CORRECT: False, CUM_PROB: 0.25
TOTAL: 72/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 3, STRATEGY: Fact Statement, MAX_NEW_TOKENS: 25, TEMP: 0.1, RUN: 2/5
OUTPUT_TEXT: The top speed of a Formula 1 car is 360 km/h (220 mph). The fastest speed ever recorded in a, IS_CORRECT: True, CUM_PROB: 0.5
TOTAL: 73/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 3, STRATEGY: Fact Statement, MAX_NEW_TOKENS: 25, TEMP: 0.1, RUN: 3/5
OUTPUT_TEXT: The top speed of a Formula 1 car is 360 km/h (220 mph). The fastest speed ever recorded in a, IS_CORRECT: True, CUM_PROB: 0.5
TOTAL: 74/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 3, STRATEGY: Fact Statement, MAX_NEW_TOKENS: 25, TEMP: 0.1, RUN: 4/5
OUTPUT_TEXT: Formula 1 cars are the fastest road-racing cars in the world. They are designed to go around a track as fast, IS_CORRECT: False, CUM_PROB: 0.25
TOTAL: 75/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 3, STRATEGY: Fact Statement, MAX_NEW_TOKENS: 25, TEMP: 0.1, RUN: 5/5
OUTPUT_TEXT: Formula 1 cars are the fastest road-racing cars in the world. They are designed to go around a track as fast, IS_CORRECT: False, CUM_PROB: 0.25
TOTAL: 76/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 3, STRATEGY: Completion, MAX_NEW_TOKENS: 25, TEMP: 0.1, RUN: 1/5
OUTPUT_TEXT: it depends. The answer depends on the type of business you are in, the type of customers you have, and the type, IS_CORRECT: False, CUM_PROB: 0.25314904659910553
TOTAL: 77/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 3, STRATEGY: Completion, MAX_NEW_TOKENS: 25, TEMP: 0.1, RUN: 2/5
OUTPUT_TEXT: it depends. The answer depends on the type of business you are in, the type of customers you have, and the type, IS_CORRECT: False, CUM_PROB: 0.25314904659910553
TOTAL: 78/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 3, STRATEGY: Completion, MAX_NEW_TOKENS: 25, TEMP: 0.1, RUN: 3/5
OUTPUT_TEXT: yes, you can. But you need to be careful. The reason is that the IRS has a very strict definition of what, IS_CORRECT: False, CUM_PROB: 0.02163809989662724
TOTAL: 79/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 3, STRATEGY: Completion, MAX_NEW_TOKENS: 25, TEMP: 0.1, RUN: 4/5
OUTPUT_TEXT: it depends. The, IS_CORRECT: False, CUM_PROB: 0.38864994049072266
TOTAL: 80/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 3, STRATEGY: Completion, MAX_NEW_TOKENS: 25, TEMP: 0.1, RUN: 5/5
OUTPUT_TEXT: it depends. The, IS_CORRECT: False, CUM_PROB: 0.38864994049072266
TOTAL: 81/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 4, STRATEGY: Fact Statement, MAX_NEW_TOKENS: 15, TEMP: 0.1, RUN: 1/5
OUTPUT_TEXT: The main ingredient of a Caesar salad is romaine lettuce. The dressing is, IS_CORRECT: True, CUM_PROB: 1.0
TOTAL: 82/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 4, STRATEGY: Fact Statement, MAX_NEW_TOKENS: 15, TEMP: 0.1, RUN: 2/5
OUTPUT_TEXT: The main ingredient of a Caesar salad is romaine lettuce. The dressing is, IS_CORRECT: True, CUM_PROB: 1.0
TOTAL: 83/240, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 4, STRATEGY: Fact Statement, MAX_NEW_TOKENS: 15, TEMP: 0.1, RUN: 3/5

In [6]:
# Convert the results list to a pandas DataFrame
df = pd.DataFrame(results)

# Print the DataFrame
print(df)

# Export the DataFrame to an Excel file
df.to_excel("multinomial_sampling_llama_5_runs-v2.xlsx", index=False)

                         model  \
0   meta-llama/Meta-Llama-3-8B
1   meta-llama/Meta-Llama-3-8B
2   meta-llama/Meta-Llama-3-8B
3   meta-llama/Meta-Llama-3-8B
4   meta-llama/Meta-Llama-3-8B
5   meta-llama/Meta-Llama-3-8B
6   meta-llama/Meta-Llama-3-8B
7   meta-llama/Meta-Llama-3-8B
8   meta-llama/Meta-Llama-3-8B
9   meta-llama/Meta-Llama-3-8B
10  meta-llama/Meta-Llama-3-8B
11  meta-llama/Meta-Llama-3-8B
12  meta-llama/Meta-Llama-3-8B
13  meta-llama/Meta-Llama-3-8B
14  meta-llama/Meta-Llama-3-8B
15  meta-llama/Meta-Llama-3-8B
16  meta-llama/Meta-Llama-3-8B
17  meta-llama/Meta-Llama-3-8B
18  meta-llama/Meta-Llama-3-8B
19  meta-llama/Meta-Llama-3-8B
20  meta-llama/Meta-Llama-3-8B
21  meta-llama/Meta-Llama-3-8B
22  meta-llama/Meta-Llama-3-8B
23  meta-llama/Meta-Llama-3-8B
24  meta-llama/Meta-Llama-3-8B
25  meta-llama/Meta-Llama-3-8B
26  meta-llama/Meta-Llama-3-8B
27  meta-llama/Meta-Llama-3-8B
28  meta-llama/Meta-Llama-3-8B
29  meta-llama/Meta-Llama-3-8B
30  meta-llama/Meta-Llama-3-8B
31  meta-llama/Meta-Llama-3-8B
32  meta-llama/Meta-Llama-3-8B
33  meta-llama/Meta-Llama-3-8B
34  meta-llama/Meta-Llama-3-8B
35  meta-llama/Meta-Llama-3-8B
36  meta-llama/Meta-Llama-3-8B
37  meta-llama/Meta-Llama-3-8B
38  meta-llama/Meta-Llama-3-8B
39  meta-llama/Meta-Llama-3-8B
40  meta-llama/Meta-Llama-3-8B
41  meta-llama/Meta-Llama-3-8B
42  meta-llama/Meta-Llama-3-8B
43  meta-llama/Meta-Llama-3-8B
44  meta-llama/Meta-Llama-3-8B
45  meta-llama/Meta-Llama-3-8B
46  meta-llama/Meta-Llama-3-8B
47  meta-llama/Meta-Llama-3-8B
48  meta-llama/Meta-Llama-3-8B
49  meta-llama/Meta-Llama-3-8B
50  meta-llama/Meta-Llama-3-8B
51  meta-llama/Meta-Llama-3-8B
52  meta-llama/Meta-Llama-3-8B
53  meta-llama/Meta-Llama-3-8B
54  meta-llama/Meta-Llama-3-8B

                                                query  max_new_tokens  temp  \
0    What is the location of Simcoe Composite School?              15   0.1
1    What is the location of Simcoe Composite School?              15   0.1
2    What is the location of Simcoe Composite School?              15   0.1
3    What is the location of Simcoe Composite School?              15   0.1
4    What is the location of Simcoe Composite School?              15   0.1
5    What is the location of Simcoe Composite School?              15   0.1
6    What is the location of Simcoe Composite School?              15   0.1
7    What is the location of Simcoe Composite School?              15   0.1
8    What is the location of Simcoe Composite School?              15   0.1
9    What is the location of Simcoe Composite School?              15   0.1
10   What is the location of Simcoe Composite School?              20   0.1
11   What is the location of Simcoe Composite School?              20   0.1
12   What is the location of Simcoe Composite School?              20   0.1
13   What is the location of Simcoe Composite School?              20   0.1
14   What is the location of Simcoe Composite School?              20   0.1
15   What is the location of Simcoe Composite School?              20   0.1
16   What is the location of Simcoe Composite School?              20   0.1
17   What is the location of Simcoe Composite School?              20   0.1
18   What is the location of Simcoe Composite School?              20   0.1
19   What is the location of Simcoe Composite School?              20   0.1
20  musical. What is Alan Turing's area of expertise?              15   0.1
21  musical. What is Alan Turing's area of expertise?              15   0.1
22  musical. What is Alan Turing's area of expertise?              15   0.1
23  musical. What is Alan Turing's area of expertise?              15   0.1
24  musical. What is Alan Turing's area of expertise?              15   0.1
25  musical. What is Alan Turing's area of expertise?              15   0.1
26  musical. What is Alan Turing's area of expertise?              15   0.1
27  musical. What is Alan Turing's area of expertise?              15   0.1
28  musical. What is Alan Turing's area of expertise?              15   0.1
29  musical. What is Alan Turing's area of expertise?              15   0.1
30  musical. What is Alan Turing's area of expertise?              20   0.1
31  musical. What is Alan Turing's area of expertise?              20   0.1
32  musical. What is Alan Turing's area of expertise?              20   0.1
33  musical. What is Alan Turing's area of expertise?              20   0.1
34  musical. What is Alan Turing's area of expertise?              20   0.1
35  musical. What is Alan Turing's area of expertise?              20   0.1
36  musical. What is Alan Turing's area of expertise?              20   0.1
37  musical. What is Alan Turing's area of expertise?              20   0.1
38  musical. What is Alan Turing's area of expertise?              20   0.1
39  musical. What is Alan Turing's area of expertise?              20   0.1
40  Latin. What is the native language of Louis Ju...              15   0.1
41  Latin. What is the native language of Louis Ju...              15   0.1
42  Latin. What is the native language of Louis Ju...              15   0.1
43  Latin. What is the native language of Louis Ju...              15   0.1
44  Latin. What is the native language of Louis Ju...              15   0.1
45  Latin. What is the native language of Louis Ju...              15   0.1
46  Latin. What is the native language of Louis Ju...              15   0.1
47  Latin. What is the native language of Louis Ju...              15   0.1
48  Latin. What is the native language of Louis Ju...              15   0.1
49  Latin. What is the native language of Louis Ju...              15   0.1
50  Latin. What is the native language of Louis Ju...              20   0.1
51  Latin. What is the native language of Louis Ju...              20   0.1
52  Latin. What is the native language of Louis Ju...              20   0.1
53  Latin. What is the native language of Louis Ju...              20   0.1
54  Latin. What is the native language of Louis Ju...              20   0.1

          strategy true_answer  \
0   Fact Statement      Canada
1   Fact Statement      Canada
2   Fact Statement      Canada
3   Fact Statement      Canada
4   Fact Statement      Canada
5       Completion      Canada
6       Completion      Canada
7       Completion      Canada
8       Completion      Canada
9       Completion      Canada
10  Fact Statement      Canada
11  Fact Statement      Canada
12  Fact Statement      Canada
13  Fact Statement      Canada
14  Fact Statement      Canada
15      Completion      Canada
16      Completion      Canada
17      Completion      Canada
18      Completion      Canada
19      Completion      Canada
20  Fact Statement       logic
21  Fact Statement       logic
22  Fact Statement       logic
23  Fact Statement       logic
24  Fact Statement       logic
25      Completion       logic
26      Completion       logic
27      Completion       logic
28      Completion       logic
29      Completion       logic
30  Fact Statement       logic
31  Fact Statement       logic
32  Fact Statement       logic
33  Fact Statement       logic
34  Fact Statement       logic
35      Completion       logic
36      Completion       logic
37      Completion       logic
38      Completion       logic
39      Completion       logic
40  Fact Statement      French
41  Fact Statement      French
42  Fact Statement      French
43  Fact Statement      French
44  Fact Statement      French
45      Completion      French
46      Completion      French
47      Completion      French
48      Completion      French
49      Completion      French
50  Fact Statement      French
51  Fact Statement      French
52  Fact Statement      French
53  Fact Statement      French
54  Fact Statement      French

                                          output_text  is_correct  cum_prob  \
0   Simcoe Composite School is located at 1 Simcoe...       False    1.0000
1   Simcoe Composite School is located at 1 Simcoe...       False    1.0000
2   Simcoe Composite School is located at 1 Simcoe...       False    1.0000
3   Simcoe Composite School is located at 1 Simcoe...       False    1.0000
4   Simcoe Composite School is located at 1 Simcoe...       False    1.0000
5                                                  it       False    0.3886
6   it depends. The answer depends on the type of ...       False    0.3886
7                                                  it       False    0.3886
8   yes, you can. But you need to be careful. You ...       False    0.0278
9                                                  it       False    0.3886
10  Simcoe Composite School is located at 1 Simcoe...       False    1.0000
11  Simcoe Composite School is located at 1 Simcoe...       False    1.0000
12  Simcoe Composite School is located at 1 Simcoe...       False    1.0000
13  Simcoe Composite School is located at 1 Simcoe...       False    1.0000
14  Simcoe Composite School is located at 1 Simcoe...       False    1.0000
15  it depends. The answer depends on the type of ...       False    0.2531
16                          it depends. The answer is       False    0.3886
17                          it depends. The answer is       False    0.3886
18  it depends. The answer depends on the type of ...       False    0.2531
19                          it depends. The answer is       False    0.3886
20  Alan Turing was a British mathematician, logic...        True    1.0000
21  Alan Turing was a British mathematician, logic...        True    1.0000
22  Alan Turing was a British mathematician, logic...        True    1.0000
23  Alan Turing was a British mathematician, logic...        True    1.0000
24  Alan Turing was a British mathematician, logic...        True    1.0000
25  it depends. The answer depends on the type of ...       False    0.3886
26                                                 it       False    0.3886
27  yes, you can. But you should be aware of the r...       False    0.0557
28                                                 it       False    0.3886
29  it depends. The answer depends on the type of ...       False    0.3886
30  Alan Turing was a British mathematician, logic...        True    0.3486
31  Alan Turing was a British mathematician, logic...        True    0.6514
32  Alan Turing was a British mathematician, logic...        True    0.6514
33  Alan Turing was a British mathematician, logic...        True    0.3486
34  Alan Turing was a British mathematician, logic...        True    0.6514
35                          it depends. The answer is       False    0.3886
36  it depends. The answer depends on the type of ...       False    0.1355
37                          it depends. The answer is       False    0.3886
38  yes, you can. But it’s not as easy as it sound...       False    0.0278
39                          it depends. The answer is       False    0.3886
40   Louis Jules Trochu is the native French Speaker.        True    0.5000
41   Louis Jules Trochu is the native French Speaker.        True    0.5000
42  Louis Jules Trochu was born on the 12th of March,       False    0.5000
43   Louis Jules Trochu is the native French Speaker.        True    0.5000
44  Louis Jules Trochu was born on the 12th of March,       False    0.5000
45  it depends. The answer depends on the type of ...       False    0.3886
46  yes, you can. But it’s not as simple as it sou...       False    0.0557
47  it depends. The answer depends on the type of ...       False    0.3886
48  it depends. The answer depends on the type of ...       False    0.3886
49  it depends. The answer depends on the type of ...       False    0.3886
50   Louis Jules Trochu is the native French Speaker.        True    0.5000
51   Louis Jules Trochu is the native French Speaker.        True    0.5000
52  Louis Jules Trochu was born on the 12th of Mar...       False    0.5000
53  Louis Jules Trochu was born on the 12th of Mar...       False    0.5000
54   Louis Jules Trochu is the native French Speaker.        True    0.5000

    adj_prob  entropy                                        token_probs  run
0     1.0000  -0.0000  [( Sim, 1.0), (coe, 1.0), ( Composite, 1.0), (...    1
1     1.0000  -0.0000  [( Sim, 1.0), (coe, 1.0), ( Composite, 1.0), (...    2
2     1.0000  -0.0000  [( Sim, 1.0), (coe, 1.0), ( Composite, 1.0), (...    3
3     1.0000  -0.0000  [( Sim, 1.0), (coe, 1.0), ( Composite, 1.0), (...    4
4     1.0000  -0.0000  [( Sim, 1.0), (coe, 1.0), ( Composite, 1.0), (...    5
5     0.9389   0.5424  [( it, 0.7773), ( depends, 1.0), (., 1.0), ( T...    1
6     0.9389   0.5424  [( it, 0.7773), ( depends, 1.0), (., 1.0), ( T...    2
7     0.9389   0.5424  [( it, 0.7773), ( depends, 1.0), (., 1.0), ( T...    3
8     0.7876   1.3742  [( yes, 0.2227), (,, 1.0), ( you, 1.0), ( can,...    4
9     0.9389   0.5424  [( it, 0.7773), ( depends, 1.0), (., 1.0), ( T...    5
10    1.0000  -0.0000  [( Sim, 1.0), (coe, 1.0), ( Composite, 1.0), (...    1
11    1.0000  -0.0000  [( Sim, 1.0), (coe, 1.0), ( Composite, 1.0), (...    2
12    1.0000  -0.0000  [( Sim, 1.0), (coe, 1.0), ( Composite, 1.0), (...    3
13    1.0000  -0.0000  [( Sim, 1.0), (coe, 1.0), ( Composite, 1.0), (...    4
14    1.0000  -0.0000  [( Sim, 1.0), (coe, 1.0), ( Composite, 1.0), (...    5
15    0.9336   0.8216  [( it, 0.7773), ( depends, 1.0), (., 1.0), ( T...    1
16    0.9538   0.5424  [( it, 0.7773), ( depends, 1.0), (., 1.0), ( T...    2
17    0.9538   0.5424  [( it, 0.7773), ( depends, 1.0), (., 1.0), ( T...    3
18    0.9336   0.8216  [( it, 0.7773), ( depends, 1.0), (., 1.0), ( T...    4
19    0.9538   0.5424  [( it, 0.7773), ( depends, 1.0), (., 1.0), ( T...    5
20    1.0000  -0.0000  [( Alan, 1.0), ( Turing, 1.0), ( was, 1.0), ( ...    1
21    1.0000  -0.0000  [( Alan, 1.0), ( Turing, 1.0), ( was, 1.0), ( ...    2
22    1.0000  -0.0000  [( Alan, 1.0), ( Turing, 1.0), ( was, 1.0), ( ...    3
23    1.0000  -0.0000  [( Alan, 1.0), ( Turing, 1.0), ( was, 1.0), ( ...    4
24    1.0000  -0.0000  [( Alan, 1.0), ( Turing, 1.0), ( was, 1.0), ( ...    5
25    0.9389   0.5424  [( it, 0.7773), ( depends, 1.0), (., 1.0), ( T...    1
26    0.9389   0.5424  [( it, 0.7773), ( depends, 1.0), (., 1.0), ( T...    2
27    0.8249   1.0276  [( yes, 0.2227), (,, 1.0), ( you, 1.0), ( can,...    3
28    0.9389   0.5424  [( it, 0.7773), ( depends, 1.0), (., 1.0), ( T...    4
29    0.9389   0.5424  [( it, 0.7773), ( depends, 1.0), (., 1.0), ( T...    5
30    0.9487   0.3674  [( Alan, 1.0), ( Turing, 1.0), ( was, 1.0), ( ...    1
31    0.9788   0.2792  [( Alan, 1.0), ( Turing, 1.0), ( was, 1.0), ( ...    2
32    0.9788   0.2792  [( Alan, 1.0), ( Turing, 1.0), ( was, 1.0), ( ...    3
33    0.9487   0.3674  [( Alan, 1.0), ( Turing, 1.0), ( was, 1.0), ( ...    4
34    0.9788   0.2792  [( Alan, 1.0), ( Turing, 1.0), ( was, 1.0), ( ...    5
35    0.9538   0.5424  [( it, 0.7773), ( depends, 1.0), (., 1.0), ( T...    1
36    0.9049   0.9098  [( it, 0.7773), ( depends, 1.0), (., 1.0), ( T...    2
37    0.9538   0.5424  [( it, 0.7773), ( depends, 1.0), (., 1.0), ( T...    3
38    0.8360   1.3742  [( yes, 0.2227), (,, 1.0), ( you, 1.0), ( can,...    4
39    0.9538   0.5424  [( it, 0.7773), ( depends, 1.0), (., 1.0), ( T...    5
40    0.9439   0.3466  [( Louis, 1.0), ( J, 1.0), (ules, 1.0), ( Tro,...    1
41    0.9439   0.3466  [( Louis, 1.0), ( J, 1.0), (ules, 1.0), ( Tro,...    2
42    0.9548   0.3466  [( Louis, 1.0), ( J, 1.0), (ules, 1.0), ( Tro,...    3
43    0.9439   0.3466  [( Louis, 1.0), ( J, 1.0), (ules, 1.0), ( Tro,...    4
44    0.9548   0.3466  [( Louis, 1.0), ( J, 1.0), (ules, 1.0), ( Tro,...    5
45    0.9389   0.5424  [( it, 0.7773), ( depends, 1.0), (., 1.0), ( T...    1
46    0.8249   1.0276  [( yes, 0.2227), (,, 1.0), ( you, 1.0), ( can,...    2
47    0.9389   0.5424  [( it, 0.7773), ( depends, 1.0), (., 1.0), ( T...    3
48    0.9389   0.5424  [( it, 0.7773), ( depends, 1.0), (., 1.0), ( T...    4
49    0.9389   0.5424  [( it, 0.7773), ( depends, 1.0), (., 1.0), ( T...    5
50    0.9439   0.3466  [( Louis, 1.0), ( J, 1.0), (ules, 1.0), ( Tro,...    1
51    0.9439   0.3466  [( Louis, 1.0), ( J, 1.0), (ules, 1.0), ( Tro,...    2
52    0.9659   0.3466  [( Louis, 1.0), ( J, 1.0), (ules, 1.0), ( Tro,...    3
53    0.9659   0.3466  [( Louis, 1.0), ( J, 1.0), (ules, 1.0), ( Tro,...    4
54    0.9439   0.3466  [( Louis, 1.0), ( J, 1.0), (ules, 1.0), ( Tro,...    5

In [ ]:
df.groupby(["model", "strategy", "max_new_tokens", "temp"]).agg({
    "is_correct": ["sum"],
    "cum_prob": ["mean"]
}).to_excel("results_07_31_v2_agg.xlsx")

### 3.4 Beam + Multinomial

In [4]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, GenerationConfig
import pandas as pd
import numpy as np
from sklearn.metrics import roc_auc_score, average_precision_score

def get_prompt(query, strategy):
    if strategy == "Fact Statement":
        return f"{query} Fact:"
    elif strategy == "Completion":
        return f"{query} The answer is:"
    elif strategy == "Definitive Statement":
        return f"The answer to the question '{query}' is:"
    elif strategy == "Fill-in-the-Blank":
        return f"{query} is located in _____.\nAnswer:"
    elif strategy == "Structured Answer Prompt":
        return f"Question: {query}\nAnswer (one word):"
    elif strategy == "Direct Instruction":
        return f"Please answer the following question in one word.\nQuestion: {query}\nAnswer:"
    elif strategy == "Contextual Prompts":
        return f"{query} (Please answer in one word)"
    elif strategy == "Question-Answer Pairs":
        return f"QSTN: What is the capital of France?\nANSR: Paris\nQSTN: What is the capital of Germany?\nANSR: Berlin\nQSTN: {query}\nANSR:"
    elif strategy == "Direct Answer":
        return f"Please provide a short, direct answer to the following question: {query} Answer:"
    elif strategy == "Q&A Format":
        return f"Q: {query}\nA:"
    elif strategy == "Instructional":
        return f"Answer the following question in one or two words: {query}"
    elif strategy == "Summary":
        return f"Summarize the answer to the following question: {query}"
    elif strategy == "Echo":
        return f"{query} {query}"
    elif strategy == "True Completion":
        return f"{query} The true answer is:"
    elif strategy == "Direct Completion":
        return f"{query} Answer:"
    elif strategy == "Answer Completion":
        return f"{query} The correct answer is:"
    else:
        return query

def clean_response(output_text, strategy):
    if strategy == "Fact Statement":
        return output_text.split("Fact:")[-1].strip()
    elif strategy == "Completion":
        return output_text.split("The answer is:")[-1].strip()
    elif strategy == "Definitive Statement":
        return output_text.split("is:")[-1].strip()
    elif strategy == "Fill-in-the-Blank":
        return output_text.split("Answer:")[-1].strip()
    elif strategy == "Structured Answer Prompt":
        return output_text.split("Answer (one word):")[-1].strip()
    elif strategy == "Direct Instruction":
        return output_text.split("Answer:")[-1].strip()
    elif strategy == "Contextual Prompts":
        return output_text.split("Please answer in one word")[-1].strip()
    elif strategy == "Question-Answer Pairs":
        return output_text.split("ANSR:")[-1].strip()
    elif strategy == "Direct Answer":
        return output_text.split("Answer:")[-1].strip()
    elif strategy == "Q&A Format":
        return output_text.split("A:")[-1].strip()
    elif strategy == "Instructional":
        return output_text.split("Answer the following question")[-1].strip()
    elif strategy == "Summary":
        return output_text.split("Summarize the answer to the following question")[-1].strip()
    elif strategy == "Echo":
        return output_text
    elif strategy == "True Completion":
        return output_text.split("The true answer is:")[-1].strip()
    elif strategy == "Direct Completion":
        return output_text.split("Answer:")[-1].strip()
    elif strategy == "Answer Completion":
        return output_text.split("The correct answer is:")[-1].strip()
    else:
        return output_text.strip()

def calculate_entropy(probs):
    return -np.sum(probs * np.log(probs))

class ResponseGenerator:
    def __init__(self, model_name):
        self.tokenizer = AutoTokenizer.from_pretrained(model_name, device_map="cuda")
        self.model = AutoModelForCausalLM.from_pretrained(model_name, torch_dtype="auto", device_map="cuda")
        
        # Set pad_token_id to eos_token_id to avoid the warning
        self.tokenizer.pad_token_id = self.tokenizer.eos_token_id
        self.model.eval()

    def generate_response(self, query, strategy, true_answer, max_new_tokens, temperature, use_beam_search, n_repeats=5, n_beams=5):
        prompt = get_prompt(query, strategy)
        inputs = self.tokenizer(prompt, return_tensors='pt').to("cuda")
        
        # Generation configuration
        generation_config = {
            "temperature": temperature,
            "do_sample": True,
            "top_p": 0.75,
            "top_k": 40,
            "output_scores": True,
            "output_hidden_states": False,
            "output_attentions": False,
            "return_dict_in_generate": True,
            "pad_token_id": self.tokenizer.eos_token_id
        }
        
        if use_beam_search:
            generation_config = {
                **generation_config,
                "num_beams": n_beams,
                "num_return_sequences": n_beams,
            }
            generation_config.pop("do_sample")
        
        results = []

        if use_beam_search:
            with torch.no_grad():
                outputs = self.model.generate(
                    inputs['input_ids'],
                    attention_mask=inputs['attention_mask'],  # Provide attention_mask to avoid the warning
                    generation_config=GenerationConfig(**generation_config),
                    max_new_tokens=max_new_tokens
                )
            transition_scores = self.model.compute_transition_scores(
                outputs.sequences,
                outputs.scores,
                normalize_logits=True,
                beam_indices=outputs.beam_indices
            )
            trans_scores = np.exp(transition_scores.cpu().numpy())

            for i in range(n_beams):  # Process each beam
                output_text = self.tokenizer.decode(outputs.sequences[i], skip_special_tokens=True)
                output_text = clean_response(output_text, strategy)

                token_probs = [(self.tokenizer.decode([outputs.sequences[i][j]]), round(trans_scores[i, j], 4))
                               for j in range(len(trans_scores[i]))]

                beam_prob = torch.exp(torch.sum(torch.log(torch.from_numpy(trans_scores[i])))).cpu().item()
                beam_prob_adj = torch.exp((len(trans_scores[0]) ** -1) * torch.sum(torch.log(torch.from_numpy(trans_scores[i])))).cpu().item()

                entropy = calculate_entropy(np.array(trans_scores[i]))
                is_correct = true_answer.lower() in output_text.lower()

                results.append({
                    "output_text": output_text,
                    "beam_prob": beam_prob,
                    "beam_prob_adj": beam_prob_adj,
                    "entropy": entropy,
                    "is_correct": is_correct,
                    "token_probs": token_probs,
                    "run": i + 1  # 1-indexed
                })

        else:
            for run in range(n_repeats):
                with torch.no_grad():
                    outputs = self.model.generate(
                        inputs['input_ids'],
                        attention_mask=inputs['attention_mask'],
                        generation_config=GenerationConfig(**generation_config),
                        max_new_tokens=max_new_tokens
                    )

                output_text = self.tokenizer.decode(outputs.sequences[0], skip_special_tokens=True)
                output_text = clean_response(output_text, strategy)

                response_tokens = outputs.sequences[0].tolist()
                probs = []
                sequence = outputs.sequences[0]
                shift_idx = len(sequence) - len(outputs.scores)  # Position to start processing tokens
                token_probs = []

                for pos_idx, beam_scores in enumerate(outputs.scores):
                    softmax_scores = torch.softmax(beam_scores, dim=-1)
                    token_id = sequence[pos_idx + shift_idx]
                    token_prob = softmax_scores[0][token_id].item()
                    token_probs.append((self.tokenizer.decode([token_id]), round(token_prob, 4)))
                    probs.append(token_prob)

                probs = torch.tensor(probs)
                beam_prob = torch.exp(torch.sum(torch.log(probs))).item()
                beam_prob_adj = torch.exp((len(probs) ** -1) * torch.sum(torch.log(probs))).item()

                entropy = calculate_entropy(np.array(probs))
                is_correct = true_answer.lower() in output_text.lower()

                results.append({
                    "output_text": output_text,
                    "beam_prob": beam_prob,
                    "beam_prob_adj": beam_prob_adj,
                    "entropy": entropy,
                    "is_correct": is_correct,
                    "token_probs": token_probs,
                    "run": run + 1  # 1-indexed
                })

        return results

# Example usage:
model_names = [
    #"bigscience/bloomz-560m",
    "meta-llama/Meta-Llama-3-8B",
    #"meta-llama/Meta-Llama-3-8B-Instruct",
    "bigscience/bloomz-1b1",
    "openai-community/gpt2-large",
    #"EleutherAI/gpt-neo-1.3B",
    "TinyLlama/TinyLlama_v1.1",
    "TinyLlama/TinyLlama-1.1B-Chat-v1.0",
]
queries_and_answers = [
    # Place / Region Names (3)
    ("What is the location of the Great Wall of China?", "China"),
    ("Where is the Eiffel Tower located?", "Paris"),
    ("What is the capital city of Japan?", "Tokyo"),
    
    # Adjectives (3)
    ("How would you describe the taste of a lemon?", "Sour"),
    ("What is the best way to describe the weather on a clear day?", "Sunny"),
    ("How would you describe the feeling of touching velvet?", "Soft"),
    
    # Person Names (3)
    ("Who was the first president of the United States?", "George Washington"),
    ("Who is the author of 'Pride and Prejudice'?", "Jane Austen"),
    ("Who painted the Mona Lisa?", "Leonardo da Vinci"),
    
    # Abstract Answers (3)
    ("What is your favorite color?", "I don't know"),
    ("What do you think of the meaning of life?", "It's complicated"),
    ("What comes after the end?", "Nothing"),
    
    # Numerical Answers (3)
    ("How many continents are there on Earth?", "Seven"),
    ("What is the boiling point of water in Celsius?", "100"),
    ("How many hours are there in a day?", "24"),
    
    # Languages (3)
    ("What language is primarily spoken in Brazil?", "Portuguese"),
    ("Which language is spoken in Germany?", "German"),
    ("What is the official language of China?", "Mandarin"),
    
    # Company Names (3)
    ("Which company developed the iPhone?", "Apple"),
    ("What is the name of the online retailer founded by Jeff Bezos?", "Amazon"),
    ("Which company is known for its search engine?", "Google")
]

# max_new_tokens_list = [10, 15, 20, 30, 40]
max_new_tokens_list = [10, 15, 20, 30, 40]
temperature_list = [0.1]
strategies = [
    "Fact Statement",
    "Completion",
    "Definitive Statement",
    "Fill-in-the-Blank",
    "Structured Answer Prompt",
    "Direct Instruction",
    "Contextual Prompts",
    "Question-Answer Pairs",
    "Direct Answer",
    "Q&A Format",
    "Instructional",
    "Summary",
    "Echo",
    "True Completion",
    "Direct Completion",
    "Answer Completion"
]

n_repeats = 5
use_beam_search_list = [True, False]

# Initialize a list to store the results
results = []

n_steps = 0
total_steps = len(model_names) * len(queries_and_answers) * len(max_new_tokens_list) * len(temperature_list) * len(strategies) * n_repeats * len(use_beam_search_list)
for model_name in model_names:
    generator = ResponseGenerator(model_name)
    for query_idx, (query, true_answer) in enumerate(queries_and_answers):
        for max_new_tokens in max_new_tokens_list:
            for temperature in temperature_list:
                for strategy in strategies:
                    for use_beam_search in use_beam_search_list:  # Iterate over Beam Search and Multinomial Sampling
                        run_results = generator.generate_response(query, strategy, true_answer, max_new_tokens, temperature, use_beam_search, n_repeats=n_repeats, n_beams=n_repeats)
                        for result_dict in run_results:
                            print(f"TOTAL: {n_steps + 1}/{total_steps}, MODEL: {model_name}, QUERY: {query_idx}, STRATEGY: {strategy}, MAX_NEW_TOKENS: {max_new_tokens}, RUN: {result_dict['run']}/{n_repeats}")
                            # Store the results in the list
                            results.append({
                                "Model": model_name,
                                "Query": query,
                                "Strategy": strategy,
                                "Max New Tokens": max_new_tokens,
                                "Temperature": temperature,
                                "Beam Search": use_beam_search,
                                "Run": result_dict['run'],
                                "Generated Response": result_dict['output_text'],
                                "P": result_dict['beam_prob'],
                                "P_adj": result_dict['beam_prob_adj'],
                                "Entropy": result_dict['entropy'],
                                "Is Correct": result_dict['is_correct'],
                                "Token Probabilities": result_dict['token_probs']
                            })
                            print(f"IS_CORRECT: {result_dict['is_correct']}, PROB: {result_dict['beam_prob']}, ADJ_PROB: {result_dict['beam_prob_adj']}, ENTROPY: {result_dict['entropy']}")
                            n_steps += 1
                            if n_steps >= 100:
                                # pass

                                df_results = pd.DataFrame(results)
                                df_results.to_excel("beam_multinomial_llama_08_21_test-raw_table.xlsx", index=False)

                                df_results = pd.DataFrame(results)

                                def calculate_scores(group):
                                    y_true = group['Is Correct'].values
                                    y_scores = group['P'].values
                                    
                                    # Ensure at least two classes are present for AUROC
                                    if len(set(y_true)) > 1:
                                        aucroc = roc_auc_score(y_true, y_scores)
                                    else:
                                        aucroc = np.nan
                                    
                                    aucpr = average_precision_score(y_true, y_scores)
                                    accuracy = np.mean(y_true)
                                    
                                    return pd.Series({'AUROC Score': aucroc, 'AUCPR Score': aucpr, 'Accuracy': accuracy})

                                # Group by the relevant columns and calculate AUROC, AUCPR, and accuracy for each group
                                df_scores = df_results.groupby(['Model', 'Max New Tokens', 'Temperature', 'Strategy', 'Beam Search']).apply(calculate_scores).reset_index()
                                df_results = df_results.merge(df_scores, on=['Model', 'Max New Tokens', 'Temperature', 'Strategy', 'Beam Search'])

                                # Save the original detailed results to an Excel file
                                df_results.to_excel("beam_multinomial_llama_08_21_test-table.xlsx", index=False)
                                df_scores.to_excel("beam_multinomial_llama_08_21_test-scores.xlsx", index=False)
                                
                                raise KeyboardInterrupt

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading checkpoint shards: 100%|██████████| 4/4 [00:04<00:00,  1.02s/it]
/nfs/students/daro/miniconda3/envs/env-quant-rel-310/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:515: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.1` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
/nfs/students/daro/miniconda3/envs/env-quant-rel-310/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:520: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.75` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
/nfs/students/daro/miniconda3/envs/env-quant-rel-310/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:537: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `40` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
/nfs/students/daro/miniconda3/envs/env-quant-rel-310/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:515: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.1` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/nfs/students/daro/miniconda3/envs/env-quant-rel-310/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:520: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.75` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
/nfs/students/daro/miniconda3/envs/env-quant-rel-310/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:537: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `40` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

TOTAL: 1/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Fact Statement, MAX_NEW_TOKENS: 10, RUN: 1/5
IS_CORRECT: True, PROB: 0.007930183783173561, ADJ_PROB: 0.6164932250976562, ENTROPY: 2.0676867961883545
TOTAL: 2/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Fact Statement, MAX_NEW_TOKENS: 10, RUN: 2/5
IS_CORRECT: True, PROB: 0.005730344448238611, ADJ_PROB: 0.5967852473258972, ENTROPY: 1.9738126993179321
TOTAL: 3/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Fact Statement, MAX_NEW_TOKENS: 10, RUN: 3/5
IS_CORRECT: True, PROB: 0.004067429341375828, ADJ_PROB: 0.5766761898994446, ENTROPY: 2.3833987712860107
TOTAL: 4/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Fact Statement, MAX_NEW_TOKENS: 10, RUN: 4/5
IS_CORRECT: True, PROB: 0.003088973928242922, ADJ_PROB: 0.5610239505767822, ENTROPY: 2.336489200592041
TOTAL: 5/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Fact Statement, MAX_NEW_TOKENS: 10, RUN: 5/5
IS_CORRECT: True, PROB: 0.002522336319088936, ADJ_PROB: 0.5497690439224243, ENTROPY: 2.0350632667541504

/tmp/ipykernel_181463/3452781674.py:187: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  entropy = calculate_entropy(np.array(probs))

TOTAL: 6/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Fact Statement, MAX_NEW_TOKENS: 10, RUN: 1/5
IS_CORRECT: True, PROB: 1.0, ADJ_PROB: 1.0, ENTROPY: -0.0
TOTAL: 7/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Fact Statement, MAX_NEW_TOKENS: 10, RUN: 2/5
IS_CORRECT: True, PROB: 1.0, ADJ_PROB: 1.0, ENTROPY: -0.0
TOTAL: 8/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Fact Statement, MAX_NEW_TOKENS: 10, RUN: 3/5
IS_CORRECT: True, PROB: 1.0, ADJ_PROB: 1.0, ENTROPY: -0.0
TOTAL: 9/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Fact Statement, MAX_NEW_TOKENS: 10, RUN: 4/5
IS_CORRECT: True, PROB: 1.0, ADJ_PROB: 1.0, ENTROPY: -0.0
TOTAL: 10/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Fact Statement, MAX_NEW_TOKENS: 10, RUN: 5/5
IS_CORRECT: True, PROB: 1.0, ADJ_PROB: 1.0, ENTROPY: -0.0
TOTAL: 11/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Completion, MAX_NEW_TOKENS: 10, RUN: 1/5
IS_CORRECT: True, PROB: 0.0070529961958527565, ADJ_PROB: 0.609308660030365, ENTROPY: 2.109490394592285
TOTAL: 12/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Completion, MAX_NEW_TOKENS: 10, RUN: 2/5
IS_CORRECT: True, PROB: 0.006651269271969795, ADJ_PROB: 0.6057458519935608, ENTROPY: 2.0693576335906982
TOTAL: 13/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Completion, MAX_NEW_TOKENS: 10, RUN: 3/5
IS_CORRECT: True, PROB: 0.006414967123419046, ADJ_PROB: 0.6035585999488831, ENTROPY: 2.00669002532959
TOTAL: 14/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Completion, MAX_NEW_TOKENS: 10, RUN: 4/5
IS_CORRECT: True, PROB: 0.003638769034296274, ADJ_PROB: 0.5702896118164062, ENTROPY: 1.9415706396102905
TOTAL: 15/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Completion, MAX_NEW_TOKENS: 10, RUN: 5/5
IS_CORRECT: True, PROB: 0.002260196954011917, ADJ_PROB: 0.5437692403793335, ENTROPY: 1.9880952835083008
TOTAL: 16/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Completion, MAX_NEW_TOKENS: 10, RUN: 1/5
IS_CORRECT: True, PROB: 1.0, ADJ_PROB: 1.0, ENTROPY: -0.0
TOTAL: 17/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Completion, MAX_NEW_TOKENS: 10, RUN: 2/5
IS_CORRECT: True, PROB: 1.0, ADJ_PROB: 1.0, ENTROPY: -0.0
TOTAL: 18/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Completion, MAX_NEW_TOKENS: 10, RUN: 3/5
IS_CORRECT: True, PROB: 1.0, ADJ_PROB: 1.0, ENTROPY: -0.0
TOTAL: 19/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Completion, MAX_NEW_TOKENS: 10, RUN: 4/5
IS_CORRECT: True, PROB: 1.0, ADJ_PROB: 1.0, ENTROPY: -0.0
TOTAL: 20/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Completion, MAX_NEW_TOKENS: 10, RUN: 5/5
IS_CORRECT: True, PROB: 1.0, ADJ_PROB: 1.0, ENTROPY: -0.0
TOTAL: 21/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Definitive Statement, MAX_NEW_TOKENS: 10, RUN: 1/5
IS_CORRECT: True, PROB: 0.0019071504939347506, ADJ_PROB: 0.5346117615699768, ENTROPY: 2.2080721855163574
TOTAL: 22/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Definitive Statement, MAX_NEW_TOKENS: 10, RUN: 2/5
IS_CORRECT: True, PROB: 0.001529557746835053, ADJ_PROB: 0.5229456424713135, ENTROPY: 1.9138355255126953
TOTAL: 23/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Definitive Statement, MAX_NEW_TOKENS: 10, RUN: 3/5
IS_CORRECT: True, PROB: 0.0010448304237797856, ADJ_PROB: 0.5033899545669556, ENTROPY: 2.311169147491455
TOTAL: 24/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Definitive Statement, MAX_NEW_TOKENS: 10, RUN: 4/5
IS_CORRECT: True, PROB: 0.000885906454641372, ADJ_PROB: 0.4951522946357727, ENTROPY: 2.2421083450317383
TOTAL: 25/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Definitive Statement, MAX_NEW_TOKENS: 10, RUN: 5/5
IS_CORRECT: True, PROB: 0.0006337217055261135, ADJ_PROB: 0.4788393974304199, ENTROPY: 2.2553181648254395
TOTAL: 26/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Definitive Statement, MAX_NEW_TOKENS: 10, RUN: 1/5
IS_CORRECT: True, PROB: 1.0, ADJ_PROB: 1.0, ENTROPY: -0.0
TOTAL: 27/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Definitive Statement, MAX_NEW_TOKENS: 10, RUN: 2/5
IS_CORRECT: True, PROB: 1.0, ADJ_PROB: 1.0, ENTROPY: -0.0
TOTAL: 28/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Definitive Statement, MAX_NEW_TOKENS: 10, RUN: 3/5
IS_CORRECT: True, PROB: 1.0, ADJ_PROB: 1.0, ENTROPY: -0.0
TOTAL: 29/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Definitive Statement, MAX_NEW_TOKENS: 10, RUN: 4/5
IS_CORRECT: True, PROB: 1.0, ADJ_PROB: 1.0, ENTROPY: -0.0
TOTAL: 30/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Definitive Statement, MAX_NEW_TOKENS: 10, RUN: 5/5
IS_CORRECT: True, PROB: 1.0, ADJ_PROB: 1.0, ENTROPY: -0.0
TOTAL: 31/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Fill-in-the-Blank, MAX_NEW_TOKENS: 10, RUN: 1/5
IS_CORRECT: True, PROB: 0.0689224898815155, ADJ_PROB: 0.7653077244758606, ENTROPY: 0.27664604783058167
TOTAL: 32/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Fill-in-the-Blank, MAX_NEW_TOKENS: 10, RUN: 2/5
IS_CORRECT: True, PROB: 0.012716392055153847, ADJ_PROB: 0.6463033556938171, ENTROPY: 1.6859406232833862
TOTAL: 33/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Fill-in-the-Blank, MAX_NEW_TOKENS: 10, RUN: 3/5
IS_CORRECT: True, PROB: 0.008739843964576721, ADJ_PROB: 0.6225157976150513, ENTROPY: 1.6969084739685059
TOTAL: 34/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Fill-in-the-Blank, MAX_NEW_TOKENS: 10, RUN: 4/5
IS_CORRECT: True, PROB: 0.007761230226606131, ADJ_PROB: 0.6151670217514038, ENTROPY: 1.2997279167175293
TOTAL: 35/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Fill-in-the-Blank, MAX_NEW_TOKENS: 10, RUN: 5/5
IS_CORRECT: True, PROB: 0.003283730009570718, ADJ_PROB: 0.5644646286964417, ENTROPY: 1.5421768426895142
TOTAL: 36/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Fill-in-the-Blank, MAX_NEW_TOKENS: 10, RUN: 1/5
IS_CORRECT: True, PROB: 1.0, ADJ_PROB: 1.0, ENTROPY: -0.0
TOTAL: 37/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Fill-in-the-Blank, MAX_NEW_TOKENS: 10, RUN: 2/5
IS_CORRECT: True, PROB: 1.0, ADJ_PROB: 1.0, ENTROPY: -0.0
TOTAL: 38/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Fill-in-the-Blank, MAX_NEW_TOKENS: 10, RUN: 3/5
IS_CORRECT: True, PROB: 1.0, ADJ_PROB: 1.0, ENTROPY: -0.0
TOTAL: 39/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Fill-in-the-Blank, MAX_NEW_TOKENS: 10, RUN: 4/5
IS_CORRECT: True, PROB: 1.0, ADJ_PROB: 1.0, ENTROPY: -0.0
TOTAL: 40/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Fill-in-the-Blank, MAX_NEW_TOKENS: 10, RUN: 5/5
IS_CORRECT: True, PROB: 1.0, ADJ_PROB: 1.0, ENTROPY: -0.0
TOTAL: 41/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Structured Answer Prompt, MAX_NEW_TOKENS: 10, RUN: 1/5
IS_CORRECT: True, PROB: 0.0018132379045709968, ADJ_PROB: 0.5319189429283142, ENTROPY: 1.7066967487335205
TOTAL: 42/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Structured Answer Prompt, MAX_NEW_TOKENS: 10, RUN: 2/5
IS_CORRECT: True, PROB: 0.0013459569308906794, ADJ_PROB: 0.516301155090332, ENTROPY: 1.506354808807373
TOTAL: 43/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Structured Answer Prompt, MAX_NEW_TOKENS: 10, RUN: 3/5
IS_CORRECT: True, PROB: 0.000528202683199197, ADJ_PROB: 0.4701972007751465, ENTROPY: 2.0351979732513428
TOTAL: 44/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Structured Answer Prompt, MAX_NEW_TOKENS: 10, RUN: 4/5
IS_CORRECT: True, PROB: 0.0005195013363845646, ADJ_PROB: 0.4694168269634247, ENTROPY: 1.6442558765411377
TOTAL: 45/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Structured Answer Prompt, MAX_NEW_TOKENS: 10, RUN: 5/5
IS_CORRECT: True, PROB: 0.00038562327972613275, ADJ_PROB: 0.455634206533432, ENTROPY: 1.4372295141220093
TOTAL: 46/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Structured Answer Prompt, MAX_NEW_TOKENS: 10, RUN: 1/5
IS_CORRECT: False, PROB: 0.5, ADJ_PROB: 0.9330329895019531, ENTROPY: 0.3465735912322998
TOTAL: 47/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Structured Answer Prompt, MAX_NEW_TOKENS: 10, RUN: 2/5
IS_CORRECT: True, PROB: 0.5, ADJ_PROB: 0.9330329895019531, ENTROPY: 0.3465735912322998
TOTAL: 48/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Structured Answer Prompt, MAX_NEW_TOKENS: 10, RUN: 3/5
IS_CORRECT: True, PROB: 0.5, ADJ_PROB: 0.9330329895019531, ENTROPY: 0.3465735912322998
TOTAL: 49/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Structured Answer Prompt, MAX_NEW_TOKENS: 10, RUN: 4/5
IS_CORRECT: False, PROB: 0.5, ADJ_PROB: 0.9330329895019531, ENTROPY: 0.3465735912322998
TOTAL: 50/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Structured Answer Prompt, MAX_NEW_TOKENS: 10, RUN: 5/5
IS_CORRECT: False, PROB: 0.5, ADJ_PROB: 0.9330329895019531, ENTROPY: 0.3465735912322998
TOTAL: 51/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Direct Instruction, MAX_NEW_TOKENS: 10, RUN: 1/5
IS_CORRECT: True, PROB: 0.004810720682144165, ADJ_PROB: 0.5864365100860596, ENTROPY: 1.7625024318695068
TOTAL: 52/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Direct Instruction, MAX_NEW_TOKENS: 10, RUN: 2/5
IS_CORRECT: True, PROB: 0.0020054068882018328, ADJ_PROB: 0.5373042225837708, ENTROPY: 1.7824902534484863
TOTAL: 53/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Direct Instruction, MAX_NEW_TOKENS: 10, RUN: 3/5
IS_CORRECT: True, PROB: 0.0012516699498519301, ADJ_PROB: 0.512565016746521, ENTROPY: 1.321290135383606
TOTAL: 54/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Direct Instruction, MAX_NEW_TOKENS: 10, RUN: 4/5
IS_CORRECT: True, PROB: 0.0009953767294064164, ADJ_PROB: 0.5009550452232361, ENTROPY: 1.603595495223999
TOTAL: 55/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Direct Instruction, MAX_NEW_TOKENS: 10, RUN: 5/5
IS_CORRECT: True, PROB: 0.0005719970213249326, ADJ_PROB: 0.47395744919776917, ENTROPY: 1.6413934230804443
TOTAL: 56/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Direct Instruction, MAX_NEW_TOKENS: 10, RUN: 1/5
IS_CORRECT: True, PROB: 1.0, ADJ_PROB: 1.0, ENTROPY: -0.0
TOTAL: 57/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Direct Instruction, MAX_NEW_TOKENS: 10, RUN: 2/5
IS_CORRECT: True, PROB: 1.0, ADJ_PROB: 1.0, ENTROPY: -0.0
TOTAL: 58/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Direct Instruction, MAX_NEW_TOKENS: 10, RUN: 3/5
IS_CORRECT: True, PROB: 1.0, ADJ_PROB: 1.0, ENTROPY: -0.0
TOTAL: 59/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Direct Instruction, MAX_NEW_TOKENS: 10, RUN: 4/5
IS_CORRECT: True, PROB: 1.0, ADJ_PROB: 1.0, ENTROPY: -0.0
TOTAL: 60/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Direct Instruction, MAX_NEW_TOKENS: 10, RUN: 5/5
IS_CORRECT: True, PROB: 1.0, ADJ_PROB: 1.0, ENTROPY: -0.0
TOTAL: 61/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Contextual Prompts, MAX_NEW_TOKENS: 10, RUN: 1/5
IS_CORRECT: True, PROB: 0.0009393807267770171, ADJ_PROB: 0.4980628490447998, ENTROPY: 2.195396900177002
TOTAL: 62/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Contextual Prompts, MAX_NEW_TOKENS: 10, RUN: 2/5
IS_CORRECT: True, PROB: 0.0003915921552106738, ADJ_PROB: 0.45633459091186523, ENTROPY: 2.157273292541504
TOTAL: 63/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Contextual Prompts, MAX_NEW_TOKENS: 10, RUN: 3/5
IS_CORRECT: True, PROB: 0.0003850577340926975, ADJ_PROB: 0.455567330121994, ENTROPY: 1.8839244842529297
TOTAL: 64/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Contextual Prompts, MAX_NEW_TOKENS: 10, RUN: 4/5
IS_CORRECT: True, PROB: 0.00016323996533174068, ADJ_PROB: 0.4181023836135864, ENTROPY: 2.042518138885498
TOTAL: 65/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Contextual Prompts, MAX_NEW_TOKENS: 10, RUN: 5/5
IS_CORRECT: True, PROB: 0.00012500988668762147, ADJ_PROB: 0.40709373354911804, ENTROPY: 1.8728229999542236
TOTAL: 66/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Contextual Prompts, MAX_NEW_TOKENS: 10, RUN: 1/5
IS_CORRECT: False, PROB: 0.7772998809814453, ADJ_PROB: 0.975121796131134, ENTROPY: 0.19582441449165344
TOTAL: 67/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Contextual Prompts, MAX_NEW_TOKENS: 10, RUN: 2/5
IS_CORRECT: False, PROB: 0.7772998809814453, ADJ_PROB: 0.975121796131134, ENTROPY: 0.19582441449165344
TOTAL: 68/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Contextual Prompts, MAX_NEW_TOKENS: 10, RUN: 3/5
IS_CORRECT: True, PROB: 0.22270014882087708, ADJ_PROB: 0.8605419397354126, ENTROPY: 0.33447980880737305
TOTAL: 69/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Contextual Prompts, MAX_NEW_TOKENS: 10, RUN: 4/5
IS_CORRECT: False, PROB: 0.7772998809814453, ADJ_PROB: 0.975121796131134, ENTROPY: 0.19582441449165344
TOTAL: 70/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Contextual Prompts, MAX_NEW_TOKENS: 10, RUN: 5/5
IS_CORRECT: False, PROB: 0.7772998809814453, ADJ_PROB: 0.975121796131134, ENTROPY: 0.19582441449165344
TOTAL: 71/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Question-Answer Pairs, MAX_NEW_TOKENS: 10, RUN: 1/5
IS_CORRECT: True, PROB: 0.05692087486386299, ADJ_PROB: 0.7508050203323364, ENTROPY: 1.0412228107452393
TOTAL: 72/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Question-Answer Pairs, MAX_NEW_TOKENS: 10, RUN: 2/5
IS_CORRECT: True, PROB: 0.029661092907190323, ADJ_PROB: 0.7034264802932739, ENTROPY: 1.2388051748275757
TOTAL: 73/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Question-Answer Pairs, MAX_NEW_TOKENS: 10, RUN: 3/5
IS_CORRECT: True, PROB: 0.020385751500725746, ADJ_PROB: 0.6775364875793457, ENTROPY: 1.2157772779464722
TOTAL: 74/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Question-Answer Pairs, MAX_NEW_TOKENS: 10, RUN: 4/5
IS_CORRECT: False, PROB: 0.012505484744906425, ADJ_PROB: 0.6452233195304871, ENTROPY: 0.9352694749832153
TOTAL: 75/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Question-Answer Pairs, MAX_NEW_TOKENS: 10, RUN: 5/5
IS_CORRECT: True, PROB: 0.012433485127985477, ADJ_PROB: 0.6448508501052856, ENTROPY: 1.2803021669387817
TOTAL: 76/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Question-Answer Pairs, MAX_NEW_TOKENS: 10, RUN: 1/5
IS_CORRECT: True, PROB: 1.0, ADJ_PROB: 1.0, ENTROPY: -0.0
TOTAL: 77/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Question-Answer Pairs, MAX_NEW_TOKENS: 10, RUN: 2/5
IS_CORRECT: True, PROB: 1.0, ADJ_PROB: 1.0, ENTROPY: -0.0
TOTAL: 78/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Question-Answer Pairs, MAX_NEW_TOKENS: 10, RUN: 3/5
IS_CORRECT: True, PROB: 1.0, ADJ_PROB: 1.0, ENTROPY: -0.0
TOTAL: 79/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Question-Answer Pairs, MAX_NEW_TOKENS: 10, RUN: 4/5
IS_CORRECT: True, PROB: 1.0, ADJ_PROB: 1.0, ENTROPY: -0.0
TOTAL: 80/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Question-Answer Pairs, MAX_NEW_TOKENS: 10, RUN: 5/5
IS_CORRECT: True, PROB: 1.0, ADJ_PROB: 1.0, ENTROPY: -0.0
TOTAL: 81/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Direct Answer, MAX_NEW_TOKENS: 10, RUN: 1/5
IS_CORRECT: True, PROB: 0.03570933640003204, ADJ_PROB: 0.7166022658348083, ENTROPY: 1.638004183769226
TOTAL: 82/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Direct Answer, MAX_NEW_TOKENS: 10, RUN: 2/5
IS_CORRECT: True, PROB: 0.018086742609739304, ADJ_PROB: 0.6694775819778442, ENTROPY: 1.9268957376480103
TOTAL: 83/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Direct Answer, MAX_NEW_TOKENS: 10, RUN: 3/5
IS_CORRECT: True, PROB: 0.015017776750028133, ADJ_PROB: 0.6571440100669861, ENTROPY: 1.1145498752593994
TOTAL: 84/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Direct Answer, MAX_NEW_TOKENS: 10, RUN: 4/5
IS_CORRECT: True, PROB: 0.013545065186917782, ADJ_PROB: 0.6503963470458984, ENTROPY: 1.480791449546814
TOTAL: 85/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Direct Answer, MAX_NEW_TOKENS: 10, RUN: 5/5
IS_CORRECT: True, PROB: 0.011743788607418537, ADJ_PROB: 0.6411812901496887, ENTROPY: 1.935032844543457
TOTAL: 86/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Direct Answer, MAX_NEW_TOKENS: 10, RUN: 1/5
IS_CORRECT: True, PROB: 0.3333333134651184, ADJ_PROB: 0.8959584832191467, ENTROPY: 0.3662041127681732
TOTAL: 87/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Direct Answer, MAX_NEW_TOKENS: 10, RUN: 2/5
IS_CORRECT: True, PROB: 0.3333333134651184, ADJ_PROB: 0.8959584832191467, ENTROPY: 0.3662041127681732
TOTAL: 88/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Direct Answer, MAX_NEW_TOKENS: 10, RUN: 3/5
IS_CORRECT: True, PROB: 0.3333333134651184, ADJ_PROB: 0.8959584832191467, ENTROPY: 0.3662041127681732
TOTAL: 89/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Direct Answer, MAX_NEW_TOKENS: 10, RUN: 4/5
IS_CORRECT: True, PROB: 0.3333333134651184, ADJ_PROB: 0.8959584832191467, ENTROPY: 0.3662041127681732
TOTAL: 90/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Direct Answer, MAX_NEW_TOKENS: 10, RUN: 5/5
IS_CORRECT: True, PROB: 0.3333333134651184, ADJ_PROB: 0.8959584832191467, ENTROPY: 0.3662041127681732
TOTAL: 91/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Q&A Format, MAX_NEW_TOKENS: 10, RUN: 1/5
IS_CORRECT: True, PROB: 0.017126591876149178, ADJ_PROB: 0.6658357381820679, ENTROPY: 1.882925033569336
TOTAL: 92/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Q&A Format, MAX_NEW_TOKENS: 10, RUN: 2/5
IS_CORRECT: True, PROB: 0.010920342057943344, ADJ_PROB: 0.6365369558334351, ENTROPY: 1.7722127437591553
TOTAL: 93/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Q&A Format, MAX_NEW_TOKENS: 10, RUN: 3/5
IS_CORRECT: True, PROB: 0.009158954955637455, ADJ_PROB: 0.6254384517669678, ENTROPY: 2.2099130153656006
TOTAL: 94/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Q&A Format, MAX_NEW_TOKENS: 10, RUN: 4/5
IS_CORRECT: True, PROB: 0.006294851657003164, ADJ_PROB: 0.602418839931488, ENTROPY: 2.1818578243255615
TOTAL: 95/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Q&A Format, MAX_NEW_TOKENS: 10, RUN: 5/5
IS_CORRECT: True, PROB: 0.005596810951828957, ADJ_PROB: 0.5953797698020935, ENTROPY: 2.1611316204071045
TOTAL: 96/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Q&A Format, MAX_NEW_TOKENS: 10, RUN: 1/5
IS_CORRECT: True, PROB: 1.0, ADJ_PROB: 1.0, ENTROPY: -0.0
TOTAL: 97/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Q&A Format, MAX_NEW_TOKENS: 10, RUN: 2/5
IS_CORRECT: True, PROB: 1.0, ADJ_PROB: 1.0, ENTROPY: -0.0
TOTAL: 98/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Q&A Format, MAX_NEW_TOKENS: 10, RUN: 3/5
IS_CORRECT: True, PROB: 1.0, ADJ_PROB: 1.0, ENTROPY: -0.0
TOTAL: 99/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Q&A Format, MAX_NEW_TOKENS: 10, RUN: 4/5
IS_CORRECT: True, PROB: 1.0, ADJ_PROB: 1.0, ENTROPY: -0.0
TOTAL: 100/84000, MODEL: meta-llama/Meta-Llama-3-8B, QUERY: 0, STRATEGY: Q&A Format, MAX_NEW_TOKENS: 10, RUN: 5/5
IS_CORRECT: True, PROB: 1.0, ADJ_PROB: 1.0, ENTROPY: -0.0

/tmp/ipykernel_181463/3452781674.py:332: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_scores = df_results.groupby(['Model', 'Max New Tokens', 'Temperature', 'Strategy', 'Beam Search']).apply(calculate_scores).reset_index()

KeyboardInterrupt:

In [ ]:
df_results = pd.DataFrame(results)

def calculate_scores(group):
    y_true = group['Is Correct'].values
    y_scores = group['P'].values
    
    # Ensure at least two classes are present for AUROC
    if len(set(y_true)) > 1:
        aucroc = roc_auc_score(y_true, y_scores)
    else:
        aucroc = np.nan
    
    aucpr = average_precision_score(y_true, y_scores)
    accuracy = np.mean(y_true)
    
    return pd.Series({'AUROC Score': aucroc, 'AUCPR Score': aucpr, 'Accuracy': accuracy})

# Group by the relevant columns and calculate AUROC, AUCPR, and accuracy for each group
df_scores = df_results.groupby(['Model', 'Max New Tokens', 'Temperature', 'Strategy', 'Beam Search']).apply(calculate_scores).reset_index()
df_results = df_results.merge(df_scores, on=['Model', 'Max New Tokens', 'Temperature', 'Strategy', 'Beam Search'])

# Save the original detailed results to an Excel file
df_results.to_excel("beam_multinomial_llama_table_08_21.xlsx", index=False)
df_scores.to_excel("beam_multinomial_llama_scores_08_21.xlsx", index=False)

/nfs/students/daro/miniconda3/envs/env-quant-rel-310/lib/python3.10/site-packages/sklearn/metrics/_ranking.py:1030: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
/nfs/students/daro/miniconda3/envs/env-quant-rel-310/lib/python3.10/site-packages/sklearn/metrics/_ranking.py:1030: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
/nfs/students/daro/miniconda3/envs/env-quant-rel-310/lib/python3.10/site-packages/sklearn/metrics/_ranking.py:1030: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
/nfs/students/daro/miniconda3/envs/env-quant-rel-310/lib/python3.10/site-packages/sklearn/metrics/_ranking.py:1030: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
/nfs/students/daro/miniconda3/envs/env-quant-rel-310/lib/python3.10/site-packages/sklearn/metrics/_ranking.py:1030: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
/nfs/students/daro/miniconda3/envs/env-quant-rel-310/lib/python3.10/site-packages/sklearn/metrics/_ranking.py:1030: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
/nfs/students/daro/miniconda3/envs/env-quant-rel-310/lib/python3.10/site-packages/sklearn/metrics/_ranking.py:1030: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
/tmp/ipykernel_2656690/643457655.py:19: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_scores = df_results.groupby(['Model', 'Max New Tokens', 'Temperature', 'Strategy', 'Beam Search']).apply(calculate_scores).reset_index()

In [7]:
df_scores

,Model,Max New Tokens,Temperature,Strategy,Beam Search,AUROC Score,AUCPR Score,Accuracy
0,meta-llama/Meta-Llama-3-8B,15,0.1,Completion,False,NaN,-0.000000,0.0
1,meta-llama/Meta-Llama-3-8B,15,0.1,Completion,True,NaN,-0.000000,0.0
2,meta-llama/Meta-Llama-3-8B,15,0.1,Contextual Prompts,False,NaN,-0.000000,0.0
3,meta-llama/Meta-Llama-3-8B,15,0.1,Contextual Prompts,True,0.250000,0.250000,0.2
4,meta-llama/Meta-Llama-3-8B,15,0.1,Definitive Statement,False,NaN,1.000000,1.0
5,meta-llama/Meta-Llama-3-8B,15,0.1,Definitive Statement,True,0.250000,0.804167,0.8
6,meta-llama/Meta-Llama-3-8B,15,0.1,Direct Answer,False,NaN,-0.000000,0.0
7,meta-llama/Meta-Llama-3-8B,15,0.1,Direct Answer,True,0.333333,0.500000,0.4
8,meta-llama/Meta-Llama-3-8B,15,0.1,Direct Instruction,False,NaN,1.000000,1.0
9,meta-llama/Meta-Llama-3-8B,15,0.1,Direct Instruction,True,0.166667,0.366667,0.4
10,meta-llama/Meta-Llama-3-8B,15,0.1,Fact Statement,False,NaN,-0.000000,0.0
11,meta-llama/Meta-Llama-3-8B,15,0.1,Fact Statement,True,0.250000,0.804167,0.8
12,meta-llama/Meta-Llama-3-8B,15,0.1,Fill-in-the-Blank,False,0.500000,0.400000,0.4
13,meta-llama/Meta-Llama-3-8B,15,0.1,Fill-in-the-Blank,True,0.250000,0.250000,0.2
14,meta-llama/Meta-Llama-3-8B,15,0.1,Q&A Format,False,NaN,-0.000000,0.0
15,meta-llama/Meta-Llama-3-8B,15,0.1,Q&A Format,True,0.500000,0.700000,0.4
16,meta-llama/Meta-Llama-3-8B,15,0.1,Question-Answer Pairs,False,0.500000,0.200000,0.2
17,meta-llama/Meta-Llama-3-8B,15,0.1,Question-Answer Pairs,True,0.500000,0.887500,0.8
18,meta-llama/Meta-Llama-3-8B,15,0.1,Structured Answer Prompt,False,NaN,-0.000000,0.0
19,meta-llama/Meta-Llama-3-8B,15,0.1,Structured Answer Prompt,True,1.000000,1.000000,0.6

In [6]:
df_results

,Model,Query,Strategy,Max New Tokens,Temperature,Beam Search,Run,Generated Response,P,P_adj,Entropy,Is Correct,Token Probabilities,AUROC Score,AUCPR Score,Accuracy
0,meta-llama/Meta-Llama-3-8B,What is the location of Simcoe Composite School?,Fact Statement,15,0.1,True,1,"Simcoe Composite School is located in Simcoe, ...",0.000542,0.605737,3.293906,True,"[(<|begin_of_text|>, 0.3303), (What, 0.9974), ...",0.25,0.804167,0.8
1,meta-llama/Meta-Llama-3-8B,What is the location of Simcoe Composite School?,Fact Statement,15,0.1,True,2,"Simcoe Composite School is located in Simcoe, ...",0.000474,0.600333,3.114716,False,"[(<|begin_of_text|>, 0.3303), (What, 0.9974), ...",0.25,0.804167,0.8
2,meta-llama/Meta-Llama-3-8B,What is the location of Simcoe Composite School?,Fact Statement,15,0.1,True,3,"Simcoe Composite School is located in Simcoe, ...",0.000378,0.591309,3.226967,True,"[(<|begin_of_text|>, 0.3303), (What, 0.9974), ...",0.25,0.804167,0.8
3,meta-llama/Meta-Llama-3-8B,What is the location of Simcoe Composite School?,Fact Statement,15,0.1,True,4,"Simcoe Composite School is located in Simcoe, ...",0.000276,0.579117,3.184928,True,"[(<|begin_of_text|>, 0.3303), (What, 0.9974), ...",0.25,0.804167,0.8
4,meta-llama/Meta-Llama-3-8B,What is the location of Simcoe Composite School?,Fact Statement,15,0.1,True,5,"Simcoe Composite School is located in Simcoe, ...",0.000256,0.576195,3.223548,True,"[(<|begin_of_text|>, 0.3303), (What, 0.9974), ...",0.25,0.804167,0.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,meta-llama/Meta-Llama-3-8B,What is the location of Simcoe Composite School?,Q&A Format,15,0.1,False,1,Simcoe Composite School is located at 1000 Sim...,0.500000,0.954842,0.346574,False,"[( Sim, 1.0), (coe, 1.0), ( Composite, 1.0), (...",NaN,-0.000000,0.0
96,meta-llama/Meta-Llama-3-8B,What is the location of Simcoe Composite School?,Q&A Format,15,0.1,False,2,Simcoe Composite School is located at 1000 Sim...,0.500000,0.954842,0.346574,False,"[( Sim, 1.0), (coe, 1.0), ( Composite, 1.0), (...",NaN,-0.000000,0.0
97,meta-llama/Meta-Llama-3-8B,What is the location of Simcoe Composite School?,Q&A Format,15,0.1,False,3,Simcoe Composite School is located at 1000 Sim...,0.500000,0.954842,0.346574,False,"[( Sim, 1.0), (coe, 1.0), ( Composite, 1.0), (...",NaN,-0.000000,0.0
98,meta-llama/Meta-Llama-3-8B,What is the location of Simcoe Composite School?,Q&A Format,15,0.1,False,4,Simcoe Composite School is located at 1000 Sim...,0.500000,0.954842,0.346574,False,"[( Sim, 1.0), (coe, 1.0), ( Composite, 1.0), (...",NaN,-0.000000,0.0
99,meta-llama/Meta-Llama-3-8B,What is the location of Simcoe Composite School?,Q&A Format,15,0.1,False,5,Simcoe Composite School is located at 1000 Sim...,0.500000,0.954842,0.346574,False,"[( Sim, 1.0), (coe, 1.0), ( Composite, 1.0), (...",NaN,-0.000000,0.0

In [ ]:
df.to_excel("results_07_25.xlsx", index=False)

In [ ]:
df.iloc[12, :]

In [ ]:
df.loc[df['is_correct'] == False]['output_text']